-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity HW_dwt53_inverse_HW_dwt53_inverse_core is
port (
    ap_ready : OUT STD_LOGIC;
    low_read : IN STD_LOGIC_VECTOR (15 downto 0);
    low_read_23 : IN STD_LOGIC_VECTOR (15 downto 0);
    low_read_24 : IN STD_LOGIC_VECTOR (15 downto 0);
    low_read_25 : IN STD_LOGIC_VECTOR (15 downto 0);
    low_read_26 : IN STD_LOGIC_VECTOR (15 downto 0);
    low_read_27 : IN STD_LOGIC_VECTOR (15 downto 0);
    low_read_28 : IN STD_LOGIC_VECTOR (15 downto 0);
    low_read_29 : IN STD_LOGIC_VECTOR (15 downto 0);
    high_read : IN STD_LOGIC_VECTOR (15 downto 0);
    high_read_23 : IN STD_LOGIC_VECTOR (15 downto 0);
    high_read_24 : IN STD_LOGIC_VECTOR (15 downto 0);
    high_read_25 : IN STD_LOGIC_VECTOR (15 downto 0);
    high_read_26 : IN STD_LOGIC_VECTOR (15 downto 0);
    high_read_27 : IN STD_LOGIC_VECTOR (15 downto 0);
    high_read_28 : IN STD_LOGIC_VECTOR (15 downto 0);
    high_read_29 : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_8 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_9 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_10 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_11 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_12 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_13 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_14 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_15 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_rst : IN STD_LOGIC );
end;


architecture behav of HW_dwt53_inverse_HW_dwt53_inverse_core is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv17_2 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000010";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv17_1FF80 : STD_LOGIC_VECTOR (16 downto 0) := "11111111110000000";
    constant ap_const_lv8_7F : STD_LOGIC_VECTOR (7 downto 0) := "01111111";
    constant ap_const_lv8_80 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv25_0 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000000";
    constant ap_const_lv32_FFFFFF80 : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111110000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal sext_ln201_fu_198_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln190_fu_202_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln202_fu_206_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln190_1_fu_210_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln203_fu_214_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln190_2_fu_218_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln190_3_fu_222_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln204_fu_226_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln190_4_fu_230_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln190_5_fu_234_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln205_fu_238_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln190_6_fu_242_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln190_7_fu_246_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln206_fu_250_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln190_8_fu_254_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln190_9_fu_258_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln207_fu_262_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln190_10_fu_266_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln190_11_fu_270_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln208_fu_274_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln190_12_fu_278_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln190_13_fu_282_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln190_fu_202_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln210_fu_286_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln210_fu_292_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln190_13_fu_282_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln210_1_fu_296_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal trunc_ln_fu_302_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln189_fu_166_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln210_1_fu_312_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal s_fu_316_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln190_1_fu_210_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln211_fu_326_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal trunc_ln1_fu_332_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln189_1_fu_170_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln211_fu_342_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal s_1_fu_346_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln190_3_fu_222_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln212_fu_356_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln212_fu_362_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln212_1_fu_366_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal trunc_ln2_fu_372_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln189_2_fu_174_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln212_1_fu_382_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal s_2_fu_386_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln190_5_fu_234_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln213_fu_396_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln213_fu_402_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln190_2_fu_218_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln213_1_fu_406_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal trunc_ln3_fu_412_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln189_3_fu_178_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln213_1_fu_422_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal s_3_fu_426_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln190_7_fu_246_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln214_fu_436_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln214_fu_442_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln190_4_fu_230_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln214_1_fu_446_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal trunc_ln4_fu_452_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln189_4_fu_182_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln214_1_fu_462_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal s_4_fu_466_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln190_9_fu_258_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln215_fu_476_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln215_fu_482_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln190_6_fu_242_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln215_1_fu_486_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal trunc_ln5_fu_492_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln189_5_fu_186_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln215_1_fu_502_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal s_5_fu_506_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln190_11_fu_270_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln216_fu_516_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln216_fu_522_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln190_8_fu_254_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln216_1_fu_526_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal trunc_ln6_fu_532_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln189_6_fu_190_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln216_1_fu_542_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal s_6_fu_546_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln190_12_fu_278_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln217_fu_556_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln217_fu_562_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln190_10_fu_266_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln217_1_fu_566_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal trunc_ln7_fu_572_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln189_7_fu_194_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln217_1_fu_582_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal s_7_fu_586_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_fu_596_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln9_fu_606_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_fu_612_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln9_fu_630_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln9_fu_622_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln11_fu_618_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_1_fu_644_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln9_1_fu_654_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_1_fu_660_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln9_1_fu_678_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln9_2_fu_670_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln11_1_fu_666_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_fu_692_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln9_2_fu_702_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_2_fu_708_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln9_2_fu_726_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln9_4_fu_718_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln11_2_fu_714_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_3_fu_740_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln9_3_fu_750_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_3_fu_756_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln9_3_fu_774_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln9_6_fu_766_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln11_3_fu_762_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_4_fu_788_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln9_4_fu_798_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_4_fu_804_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln9_4_fu_822_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln9_8_fu_814_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln11_4_fu_810_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_5_fu_836_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln9_5_fu_846_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_5_fu_852_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln9_5_fu_870_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln9_10_fu_862_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln11_5_fu_858_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_6_fu_884_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln9_6_fu_894_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_6_fu_900_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln9_6_fu_918_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln9_12_fu_910_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln11_6_fu_906_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_7_fu_932_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln9_7_fu_942_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_7_fu_948_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln9_7_fu_966_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln9_14_fu_958_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln11_7_fu_954_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln189_8_fu_322_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln189_9_fu_352_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln228_fu_980_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_8_fu_986_p4 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln228_fu_996_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln201_fu_198_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln228_1_fu_1000_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_9_fu_1006_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal icmp_ln9_8_fu_1016_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_8_fu_1022_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln9_8_fu_1040_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln9_16_fu_1032_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln11_8_fu_1028_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln189_10_fu_392_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln229_fu_1054_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_10_fu_1060_p4 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln229_fu_1070_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln202_fu_206_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln229_1_fu_1074_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_11_fu_1080_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal icmp_ln9_9_fu_1090_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_9_fu_1096_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln9_9_fu_1114_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln9_18_fu_1106_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln11_9_fu_1102_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln189_11_fu_432_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln230_fu_1128_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_12_fu_1134_p4 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln230_fu_1144_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln203_fu_214_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln230_1_fu_1148_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_13_fu_1154_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal icmp_ln9_10_fu_1164_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_10_fu_1170_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln9_10_fu_1188_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln9_20_fu_1180_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln11_10_fu_1176_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln189_12_fu_472_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln231_fu_1202_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_14_fu_1208_p4 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln231_fu_1218_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln204_fu_226_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln231_1_fu_1222_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_15_fu_1228_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal icmp_ln9_11_fu_1238_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_11_fu_1244_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln9_11_fu_1262_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln9_22_fu_1254_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln11_11_fu_1250_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln189_13_fu_512_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln232_fu_1276_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_16_fu_1282_p4 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln232_fu_1292_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln205_fu_238_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln232_1_fu_1296_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_17_fu_1302_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal icmp_ln9_12_fu_1312_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_12_fu_1318_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln9_12_fu_1336_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln9_24_fu_1328_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln11_12_fu_1324_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln189_14_fu_552_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln233_fu_1350_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_18_fu_1356_p4 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln233_fu_1366_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln206_fu_250_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln233_1_fu_1370_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_19_fu_1376_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal icmp_ln9_13_fu_1386_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_13_fu_1392_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln9_13_fu_1410_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln9_26_fu_1402_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln11_13_fu_1398_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln189_15_fu_592_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln234_fu_1424_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_20_fu_1430_p4 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln234_fu_1440_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln207_fu_262_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln234_1_fu_1444_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_21_fu_1450_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal icmp_ln9_14_fu_1460_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_14_fu_1466_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln9_14_fu_1484_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln9_28_fu_1476_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln11_14_fu_1472_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln235_fu_1498_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_22_fu_1504_p4 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln235_fu_1514_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln208_fu_274_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln235_1_fu_1518_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_23_fu_1524_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal icmp_ln9_15_fu_1534_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_15_fu_1540_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln9_15_fu_1558_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln9_30_fu_1550_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln11_15_fu_1546_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln9_1_fu_636_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln9_17_fu_1046_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln9_3_fu_684_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln9_19_fu_1120_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln9_5_fu_732_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln9_21_fu_1194_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln9_7_fu_780_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln9_23_fu_1268_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln9_9_fu_828_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln9_25_fu_1342_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln9_11_fu_876_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln9_27_fu_1416_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln9_13_fu_924_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln9_29_fu_1490_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln9_15_fu_972_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln9_31_fu_1564_p3 : STD_LOGIC_VECTOR (7 downto 0);


begin



    add_ln210_1_fu_296_p2 <= std_logic_vector(signed(sext_ln210_fu_292_p1) + signed(sext_ln190_13_fu_282_p1));
    add_ln210_fu_286_p2 <= std_logic_vector(signed(sext_ln190_fu_202_p1) + signed(ap_const_lv17_2));
    add_ln211_fu_326_p2 <= std_logic_vector(signed(sext_ln210_fu_292_p1) + signed(sext_ln190_1_fu_210_p1));
    add_ln212_1_fu_366_p2 <= std_logic_vector(signed(sext_ln212_fu_362_p1) + signed(sext_ln190_1_fu_210_p1));
    add_ln212_fu_356_p2 <= std_logic_vector(signed(sext_ln190_3_fu_222_p1) + signed(ap_const_lv17_2));
    add_ln213_1_fu_406_p2 <= std_logic_vector(signed(sext_ln213_fu_402_p1) + signed(sext_ln190_2_fu_218_p1));
    add_ln213_fu_396_p2 <= std_logic_vector(signed(sext_ln190_5_fu_234_p1) + signed(ap_const_lv17_2));
    add_ln214_1_fu_446_p2 <= std_logic_vector(signed(sext_ln214_fu_442_p1) + signed(sext_ln190_4_fu_230_p1));
    add_ln214_fu_436_p2 <= std_logic_vector(signed(sext_ln190_7_fu_246_p1) + signed(ap_const_lv17_2));
    add_ln215_1_fu_486_p2 <= std_logic_vector(signed(sext_ln215_fu_482_p1) + signed(sext_ln190_6_fu_242_p1));
    add_ln215_fu_476_p2 <= std_logic_vector(signed(sext_ln190_9_fu_258_p1) + signed(ap_const_lv17_2));
    add_ln216_1_fu_526_p2 <= std_logic_vector(signed(sext_ln216_fu_522_p1) + signed(sext_ln190_8_fu_254_p1));
    add_ln216_fu_516_p2 <= std_logic_vector(signed(sext_ln190_11_fu_270_p1) + signed(ap_const_lv17_2));
    add_ln217_1_fu_566_p2 <= std_logic_vector(signed(sext_ln217_fu_562_p1) + signed(sext_ln190_10_fu_266_p1));
    add_ln217_fu_556_p2 <= std_logic_vector(signed(sext_ln190_12_fu_278_p1) + signed(ap_const_lv17_2));
    add_ln228_1_fu_1000_p2 <= std_logic_vector(signed(sext_ln228_fu_996_p1) + signed(sext_ln201_fu_198_p1));
    add_ln228_fu_980_p2 <= std_logic_vector(signed(sext_ln189_8_fu_322_p1) + signed(sext_ln189_9_fu_352_p1));
    add_ln229_1_fu_1074_p2 <= std_logic_vector(signed(sext_ln229_fu_1070_p1) + signed(sext_ln202_fu_206_p1));
    add_ln229_fu_1054_p2 <= std_logic_vector(signed(sext_ln189_10_fu_392_p1) + signed(sext_ln189_9_fu_352_p1));
    add_ln230_1_fu_1148_p2 <= std_logic_vector(signed(sext_ln230_fu_1144_p1) + signed(sext_ln203_fu_214_p1));
    add_ln230_fu_1128_p2 <= std_logic_vector(signed(sext_ln189_11_fu_432_p1) + signed(sext_ln189_10_fu_392_p1));
    add_ln231_1_fu_1222_p2 <= std_logic_vector(signed(sext_ln231_fu_1218_p1) + signed(sext_ln204_fu_226_p1));
    add_ln231_fu_1202_p2 <= std_logic_vector(signed(sext_ln189_12_fu_472_p1) + signed(sext_ln189_11_fu_432_p1));
    add_ln232_1_fu_1296_p2 <= std_logic_vector(signed(sext_ln232_fu_1292_p1) + signed(sext_ln205_fu_238_p1));
    add_ln232_fu_1276_p2 <= std_logic_vector(signed(sext_ln189_13_fu_512_p1) + signed(sext_ln189_12_fu_472_p1));
    add_ln233_1_fu_1370_p2 <= std_logic_vector(signed(sext_ln233_fu_1366_p1) + signed(sext_ln206_fu_250_p1));
    add_ln233_fu_1350_p2 <= std_logic_vector(signed(sext_ln189_14_fu_552_p1) + signed(sext_ln189_13_fu_512_p1));
    add_ln234_1_fu_1444_p2 <= std_logic_vector(signed(sext_ln234_fu_1440_p1) + signed(sext_ln207_fu_262_p1));
    add_ln234_fu_1424_p2 <= std_logic_vector(signed(sext_ln189_15_fu_592_p1) + signed(sext_ln189_14_fu_552_p1));
    add_ln235_1_fu_1518_p2 <= std_logic_vector(signed(sext_ln235_fu_1514_p1) + signed(sext_ln208_fu_274_p1));
    add_ln235_fu_1498_p2 <= std_logic_vector(signed(sext_ln189_15_fu_592_p1) + signed(sext_ln189_8_fu_322_p1));
    ap_ready <= ap_const_logic_1;
    ap_return_0 <= select_ln9_1_fu_636_p3;
    ap_return_1 <= select_ln9_17_fu_1046_p3;
    ap_return_10 <= select_ln9_11_fu_876_p3;
    ap_return_11 <= select_ln9_27_fu_1416_p3;
    ap_return_12 <= select_ln9_13_fu_924_p3;
    ap_return_13 <= select_ln9_29_fu_1490_p3;
    ap_return_14 <= select_ln9_15_fu_972_p3;
    ap_return_15 <= select_ln9_31_fu_1564_p3;
    ap_return_2 <= select_ln9_3_fu_684_p3;
    ap_return_3 <= select_ln9_19_fu_1120_p3;
    ap_return_4 <= select_ln9_5_fu_732_p3;
    ap_return_5 <= select_ln9_21_fu_1194_p3;
    ap_return_6 <= select_ln9_7_fu_780_p3;
    ap_return_7 <= select_ln9_23_fu_1268_p3;
    ap_return_8 <= select_ln9_9_fu_828_p3;
    ap_return_9 <= select_ln9_25_fu_1342_p3;
    icmp_ln10_10_fu_1170_p2 <= "1" when (signed(add_ln230_1_fu_1148_p2) < signed(ap_const_lv32_FFFFFF80)) else "0";
    icmp_ln10_11_fu_1244_p2 <= "1" when (signed(add_ln231_1_fu_1222_p2) < signed(ap_const_lv32_FFFFFF80)) else "0";
    icmp_ln10_12_fu_1318_p2 <= "1" when (signed(add_ln232_1_fu_1296_p2) < signed(ap_const_lv32_FFFFFF80)) else "0";
    icmp_ln10_13_fu_1392_p2 <= "1" when (signed(add_ln233_1_fu_1370_p2) < signed(ap_const_lv32_FFFFFF80)) else "0";
    icmp_ln10_14_fu_1466_p2 <= "1" when (signed(add_ln234_1_fu_1444_p2) < signed(ap_const_lv32_FFFFFF80)) else "0";
    icmp_ln10_15_fu_1540_p2 <= "1" when (signed(add_ln235_1_fu_1518_p2) < signed(ap_const_lv32_FFFFFF80)) else "0";
    icmp_ln10_1_fu_660_p2 <= "1" when (signed(s_1_fu_346_p2) < signed(ap_const_lv17_1FF80)) else "0";
    icmp_ln10_2_fu_708_p2 <= "1" when (signed(s_2_fu_386_p2) < signed(ap_const_lv17_1FF80)) else "0";
    icmp_ln10_3_fu_756_p2 <= "1" when (signed(s_3_fu_426_p2) < signed(ap_const_lv17_1FF80)) else "0";
    icmp_ln10_4_fu_804_p2 <= "1" when (signed(s_4_fu_466_p2) < signed(ap_const_lv17_1FF80)) else "0";
    icmp_ln10_5_fu_852_p2 <= "1" when (signed(s_5_fu_506_p2) < signed(ap_const_lv17_1FF80)) else "0";
    icmp_ln10_6_fu_900_p2 <= "1" when (signed(s_6_fu_546_p2) < signed(ap_const_lv17_1FF80)) else "0";
    icmp_ln10_7_fu_948_p2 <= "1" when (signed(s_7_fu_586_p2) < signed(ap_const_lv17_1FF80)) else "0";
    icmp_ln10_8_fu_1022_p2 <= "1" when (signed(add_ln228_1_fu_1000_p2) < signed(ap_const_lv32_FFFFFF80)) else "0";
    icmp_ln10_9_fu_1096_p2 <= "1" when (signed(add_ln229_1_fu_1074_p2) < signed(ap_const_lv32_FFFFFF80)) else "0";
    icmp_ln10_fu_612_p2 <= "1" when (signed(s_fu_316_p2) < signed(ap_const_lv17_1FF80)) else "0";
    icmp_ln9_10_fu_1164_p2 <= "1" when (signed(tmp_13_fu_1154_p4) > signed(ap_const_lv25_0)) else "0";
    icmp_ln9_11_fu_1238_p2 <= "1" when (signed(tmp_15_fu_1228_p4) > signed(ap_const_lv25_0)) else "0";
    icmp_ln9_12_fu_1312_p2 <= "1" when (signed(tmp_17_fu_1302_p4) > signed(ap_const_lv25_0)) else "0";
    icmp_ln9_13_fu_1386_p2 <= "1" when (signed(tmp_19_fu_1376_p4) > signed(ap_const_lv25_0)) else "0";
    icmp_ln9_14_fu_1460_p2 <= "1" when (signed(tmp_21_fu_1450_p4) > signed(ap_const_lv25_0)) else "0";
    icmp_ln9_15_fu_1534_p2 <= "1" when (signed(tmp_23_fu_1524_p4) > signed(ap_const_lv25_0)) else "0";
    icmp_ln9_1_fu_654_p2 <= "1" when (signed(tmp_1_fu_644_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln9_2_fu_702_p2 <= "1" when (signed(tmp_2_fu_692_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln9_3_fu_750_p2 <= "1" when (signed(tmp_3_fu_740_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln9_4_fu_798_p2 <= "1" when (signed(tmp_4_fu_788_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln9_5_fu_846_p2 <= "1" when (signed(tmp_5_fu_836_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln9_6_fu_894_p2 <= "1" when (signed(tmp_6_fu_884_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln9_7_fu_942_p2 <= "1" when (signed(tmp_7_fu_932_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln9_8_fu_1016_p2 <= "1" when (signed(tmp_9_fu_1006_p4) > signed(ap_const_lv25_0)) else "0";
    icmp_ln9_9_fu_1090_p2 <= "1" when (signed(tmp_11_fu_1080_p4) > signed(ap_const_lv25_0)) else "0";
    icmp_ln9_fu_606_p2 <= "1" when (signed(tmp_fu_596_p4) > signed(ap_const_lv10_0)) else "0";
    or_ln9_10_fu_1188_p2 <= (icmp_ln9_10_fu_1164_p2 or icmp_ln10_10_fu_1170_p2);
    or_ln9_11_fu_1262_p2 <= (icmp_ln9_11_fu_1238_p2 or icmp_ln10_11_fu_1244_p2);
    or_ln9_12_fu_1336_p2 <= (icmp_ln9_12_fu_1312_p2 or icmp_ln10_12_fu_1318_p2);
    or_ln9_13_fu_1410_p2 <= (icmp_ln9_13_fu_1386_p2 or icmp_ln10_13_fu_1392_p2);
    or_ln9_14_fu_1484_p2 <= (icmp_ln9_14_fu_1460_p2 or icmp_ln10_14_fu_1466_p2);
    or_ln9_15_fu_1558_p2 <= (icmp_ln9_15_fu_1534_p2 or icmp_ln10_15_fu_1540_p2);
    or_ln9_1_fu_678_p2 <= (icmp_ln9_1_fu_654_p2 or icmp_ln10_1_fu_660_p2);
    or_ln9_2_fu_726_p2 <= (icmp_ln9_2_fu_702_p2 or icmp_ln10_2_fu_708_p2);
    or_ln9_3_fu_774_p2 <= (icmp_ln9_3_fu_750_p2 or icmp_ln10_3_fu_756_p2);
    or_ln9_4_fu_822_p2 <= (icmp_ln9_4_fu_798_p2 or icmp_ln10_4_fu_804_p2);
    or_ln9_5_fu_870_p2 <= (icmp_ln9_5_fu_846_p2 or icmp_ln10_5_fu_852_p2);
    or_ln9_6_fu_918_p2 <= (icmp_ln9_6_fu_894_p2 or icmp_ln10_6_fu_900_p2);
    or_ln9_7_fu_966_p2 <= (icmp_ln9_7_fu_942_p2 or icmp_ln10_7_fu_948_p2);
    or_ln9_8_fu_1040_p2 <= (icmp_ln9_8_fu_1016_p2 or icmp_ln10_8_fu_1022_p2);
    or_ln9_9_fu_1114_p2 <= (icmp_ln9_9_fu_1090_p2 or icmp_ln10_9_fu_1096_p2);
    or_ln9_fu_630_p2 <= (icmp_ln9_fu_606_p2 or icmp_ln10_fu_612_p2);
    s_1_fu_346_p2 <= std_logic_vector(signed(sext_ln189_1_fu_170_p1) - signed(sext_ln211_fu_342_p1));
    s_2_fu_386_p2 <= std_logic_vector(signed(sext_ln189_2_fu_174_p1) - signed(sext_ln212_1_fu_382_p1));
    s_3_fu_426_p2 <= std_logic_vector(signed(sext_ln189_3_fu_178_p1) - signed(sext_ln213_1_fu_422_p1));
    s_4_fu_466_p2 <= std_logic_vector(signed(sext_ln189_4_fu_182_p1) - signed(sext_ln214_1_fu_462_p1));
    s_5_fu_506_p2 <= std_logic_vector(signed(sext_ln189_5_fu_186_p1) - signed(sext_ln215_1_fu_502_p1));
    s_6_fu_546_p2 <= std_logic_vector(signed(sext_ln189_6_fu_190_p1) - signed(sext_ln216_1_fu_542_p1));
    s_7_fu_586_p2 <= std_logic_vector(signed(sext_ln189_7_fu_194_p1) - signed(sext_ln217_1_fu_582_p1));
    s_fu_316_p2 <= std_logic_vector(signed(sext_ln189_fu_166_p1) - signed(sext_ln210_1_fu_312_p1));
    select_ln9_10_fu_862_p3 <= 
        ap_const_lv8_7F when (icmp_ln9_5_fu_846_p2(0) = '1') else 
        ap_const_lv8_80;
    select_ln9_11_fu_876_p3 <= 
        select_ln9_10_fu_862_p3 when (or_ln9_5_fu_870_p2(0) = '1') else 
        trunc_ln11_5_fu_858_p1;
    select_ln9_12_fu_910_p3 <= 
        ap_const_lv8_7F when (icmp_ln9_6_fu_894_p2(0) = '1') else 
        ap_const_lv8_80;
    select_ln9_13_fu_924_p3 <= 
        select_ln9_12_fu_910_p3 when (or_ln9_6_fu_918_p2(0) = '1') else 
        trunc_ln11_6_fu_906_p1;
    select_ln9_14_fu_958_p3 <= 
        ap_const_lv8_7F when (icmp_ln9_7_fu_942_p2(0) = '1') else 
        ap_const_lv8_80;
    select_ln9_15_fu_972_p3 <= 
        select_ln9_14_fu_958_p3 when (or_ln9_7_fu_966_p2(0) = '1') else 
        trunc_ln11_7_fu_954_p1;
    select_ln9_16_fu_1032_p3 <= 
        ap_const_lv8_7F when (icmp_ln9_8_fu_1016_p2(0) = '1') else 
        ap_const_lv8_80;
    select_ln9_17_fu_1046_p3 <= 
        select_ln9_16_fu_1032_p3 when (or_ln9_8_fu_1040_p2(0) = '1') else 
        trunc_ln11_8_fu_1028_p1;
    select_ln9_18_fu_1106_p3 <= 
        ap_const_lv8_7F when (icmp_ln9_9_fu_1090_p2(0) = '1') else 
        ap_const_lv8_80;
    select_ln9_19_fu_1120_p3 <= 
        select_ln9_18_fu_1106_p3 when (or_ln9_9_fu_1114_p2(0) = '1') else 
        trunc_ln11_9_fu_1102_p1;
    select_ln9_1_fu_636_p3 <= 
        select_ln9_fu_622_p3 when (or_ln9_fu_630_p2(0) = '1') else 
        trunc_ln11_fu_618_p1;
    select_ln9_20_fu_1180_p3 <= 
        ap_const_lv8_7F when (icmp_ln9_10_fu_1164_p2(0) = '1') else 
        ap_const_lv8_80;
    select_ln9_21_fu_1194_p3 <= 
        select_ln9_20_fu_1180_p3 when (or_ln9_10_fu_1188_p2(0) = '1') else 
        trunc_ln11_10_fu_1176_p1;
    select_ln9_22_fu_1254_p3 <= 
        ap_const_lv8_7F when (icmp_ln9_11_fu_1238_p2(0) = '1') else 
        ap_const_lv8_80;
    select_ln9_23_fu_1268_p3 <= 
        select_ln9_22_fu_1254_p3 when (or_ln9_11_fu_1262_p2(0) = '1') else 
        trunc_ln11_11_fu_1250_p1;
    select_ln9_24_fu_1328_p3 <= 
        ap_const_lv8_7F when (icmp_ln9_12_fu_1312_p2(0) = '1') else 
        ap_const_lv8_80;
    select_ln9_25_fu_1342_p3 <= 
        select_ln9_24_fu_1328_p3 when (or_ln9_12_fu_1336_p2(0) = '1') else 
        trunc_ln11_12_fu_1324_p1;
    select_ln9_26_fu_1402_p3 <= 
        ap_const_lv8_7F when (icmp_ln9_13_fu_1386_p2(0) = '1') else 
        ap_const_lv8_80;
    select_ln9_27_fu_1416_p3 <= 
        select_ln9_26_fu_1402_p3 when (or_ln9_13_fu_1410_p2(0) = '1') else 
        trunc_ln11_13_fu_1398_p1;
    select_ln9_28_fu_1476_p3 <= 
        ap_const_lv8_7F when (icmp_ln9_14_fu_1460_p2(0) = '1') else 
        ap_const_lv8_80;
    select_ln9_29_fu_1490_p3 <= 
        select_ln9_28_fu_1476_p3 when (or_ln9_14_fu_1484_p2(0) = '1') else 
        trunc_ln11_14_fu_1472_p1;
    select_ln9_2_fu_670_p3 <= 
        ap_const_lv8_7F when (icmp_ln9_1_fu_654_p2(0) = '1') else 
        ap_const_lv8_80;
    select_ln9_30_fu_1550_p3 <= 
        ap_const_lv8_7F when (icmp_ln9_15_fu_1534_p2(0) = '1') else 
        ap_const_lv8_80;
    select_ln9_31_fu_1564_p3 <= 
        select_ln9_30_fu_1550_p3 when (or_ln9_15_fu_1558_p2(0) = '1') else 
        trunc_ln11_15_fu_1546_p1;
    select_ln9_3_fu_684_p3 <= 
        select_ln9_2_fu_670_p3 when (or_ln9_1_fu_678_p2(0) = '1') else 
        trunc_ln11_1_fu_666_p1;
    select_ln9_4_fu_718_p3 <= 
        ap_const_lv8_7F when (icmp_ln9_2_fu_702_p2(0) = '1') else 
        ap_const_lv8_80;
    select_ln9_5_fu_732_p3 <= 
        select_ln9_4_fu_718_p3 when (or_ln9_2_fu_726_p2(0) = '1') else 
        trunc_ln11_2_fu_714_p1;
    select_ln9_6_fu_766_p3 <= 
        ap_const_lv8_7F when (icmp_ln9_3_fu_750_p2(0) = '1') else 
        ap_const_lv8_80;
    select_ln9_7_fu_780_p3 <= 
        select_ln9_6_fu_766_p3 when (or_ln9_3_fu_774_p2(0) = '1') else 
        trunc_ln11_3_fu_762_p1;
    select_ln9_8_fu_814_p3 <= 
        ap_const_lv8_7F when (icmp_ln9_4_fu_798_p2(0) = '1') else 
        ap_const_lv8_80;
    select_ln9_9_fu_828_p3 <= 
        select_ln9_8_fu_814_p3 when (or_ln9_4_fu_822_p2(0) = '1') else 
        trunc_ln11_4_fu_810_p1;
    select_ln9_fu_622_p3 <= 
        ap_const_lv8_7F when (icmp_ln9_fu_606_p2(0) = '1') else 
        ap_const_lv8_80;
        sext_ln189_10_fu_392_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(s_2_fu_386_p2),18));

        sext_ln189_11_fu_432_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(s_3_fu_426_p2),18));

        sext_ln189_12_fu_472_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(s_4_fu_466_p2),18));

        sext_ln189_13_fu_512_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(s_5_fu_506_p2),18));

        sext_ln189_14_fu_552_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(s_6_fu_546_p2),18));

        sext_ln189_15_fu_592_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(s_7_fu_586_p2),18));

        sext_ln189_1_fu_170_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(low_read_23),17));

        sext_ln189_2_fu_174_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(low_read_24),17));

        sext_ln189_3_fu_178_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(low_read_25),17));

        sext_ln189_4_fu_182_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(low_read_26),17));

        sext_ln189_5_fu_186_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(low_read_27),17));

        sext_ln189_6_fu_190_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(low_read_28),17));

        sext_ln189_7_fu_194_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(low_read_29),17));

        sext_ln189_8_fu_322_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(s_fu_316_p2),18));

        sext_ln189_9_fu_352_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(s_1_fu_346_p2),18));

        sext_ln189_fu_166_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(low_read),17));

    sext_ln190_10_fu_266_p0 <= high_read_28;
        sext_ln190_10_fu_266_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln190_10_fu_266_p0),18));

    sext_ln190_11_fu_270_p0 <= high_read_28;
        sext_ln190_11_fu_270_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln190_11_fu_270_p0),17));

    sext_ln190_12_fu_278_p0 <= high_read_29;
        sext_ln190_12_fu_278_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln190_12_fu_278_p0),17));

    sext_ln190_13_fu_282_p0 <= high_read_29;
        sext_ln190_13_fu_282_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln190_13_fu_282_p0),18));

    sext_ln190_1_fu_210_p0 <= high_read_23;
        sext_ln190_1_fu_210_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln190_1_fu_210_p0),18));

    sext_ln190_2_fu_218_p0 <= high_read_24;
        sext_ln190_2_fu_218_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln190_2_fu_218_p0),18));

    sext_ln190_3_fu_222_p0 <= high_read_24;
        sext_ln190_3_fu_222_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln190_3_fu_222_p0),17));

    sext_ln190_4_fu_230_p0 <= high_read_25;
        sext_ln190_4_fu_230_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln190_4_fu_230_p0),18));

    sext_ln190_5_fu_234_p0 <= high_read_25;
        sext_ln190_5_fu_234_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln190_5_fu_234_p0),17));

    sext_ln190_6_fu_242_p0 <= high_read_26;
        sext_ln190_6_fu_242_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln190_6_fu_242_p0),18));

    sext_ln190_7_fu_246_p0 <= high_read_26;
        sext_ln190_7_fu_246_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln190_7_fu_246_p0),17));

    sext_ln190_8_fu_254_p0 <= high_read_27;
        sext_ln190_8_fu_254_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln190_8_fu_254_p0),18));

    sext_ln190_9_fu_258_p0 <= high_read_27;
        sext_ln190_9_fu_258_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln190_9_fu_258_p0),17));

    sext_ln190_fu_202_p0 <= high_read;
        sext_ln190_fu_202_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln190_fu_202_p0),17));

    sext_ln201_fu_198_p0 <= high_read;
        sext_ln201_fu_198_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln201_fu_198_p0),32));

    sext_ln202_fu_206_p0 <= high_read_23;
        sext_ln202_fu_206_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln202_fu_206_p0),32));

    sext_ln203_fu_214_p0 <= high_read_24;
        sext_ln203_fu_214_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln203_fu_214_p0),32));

    sext_ln204_fu_226_p0 <= high_read_25;
        sext_ln204_fu_226_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln204_fu_226_p0),32));

    sext_ln205_fu_238_p0 <= high_read_26;
        sext_ln205_fu_238_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln205_fu_238_p0),32));

    sext_ln206_fu_250_p0 <= high_read_27;
        sext_ln206_fu_250_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln206_fu_250_p0),32));

    sext_ln207_fu_262_p0 <= high_read_28;
        sext_ln207_fu_262_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln207_fu_262_p0),32));

    sext_ln208_fu_274_p0 <= high_read_29;
        sext_ln208_fu_274_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln208_fu_274_p0),32));

        sext_ln210_1_fu_312_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln_fu_302_p4),17));

        sext_ln210_fu_292_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln210_fu_286_p2),18));

        sext_ln211_fu_342_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln1_fu_332_p4),17));

        sext_ln212_1_fu_382_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln2_fu_372_p4),17));

        sext_ln212_fu_362_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln212_fu_356_p2),18));

        sext_ln213_1_fu_422_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln3_fu_412_p4),17));

        sext_ln213_fu_402_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln213_fu_396_p2),18));

        sext_ln214_1_fu_462_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln4_fu_452_p4),17));

        sext_ln214_fu_442_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln214_fu_436_p2),18));

        sext_ln215_1_fu_502_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln5_fu_492_p4),17));

        sext_ln215_fu_482_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln215_fu_476_p2),18));

        sext_ln216_1_fu_542_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln6_fu_532_p4),17));

        sext_ln216_fu_522_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln216_fu_516_p2),18));

        sext_ln217_1_fu_582_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln7_fu_572_p4),17));

        sext_ln217_fu_562_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln217_fu_556_p2),18));

        sext_ln228_fu_996_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_8_fu_986_p4),32));

        sext_ln229_fu_1070_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_10_fu_1060_p4),32));

        sext_ln230_fu_1144_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_12_fu_1134_p4),32));

        sext_ln231_fu_1218_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_14_fu_1208_p4),32));

        sext_ln232_fu_1292_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_16_fu_1282_p4),32));

        sext_ln233_fu_1366_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_18_fu_1356_p4),32));

        sext_ln234_fu_1440_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_20_fu_1430_p4),32));

        sext_ln235_fu_1514_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_22_fu_1504_p4),32));

    tmp_10_fu_1060_p4 <= add_ln229_fu_1054_p2(17 downto 1);
    tmp_11_fu_1080_p4 <= add_ln229_1_fu_1074_p2(31 downto 7);
    tmp_12_fu_1134_p4 <= add_ln230_fu_1128_p2(17 downto 1);
    tmp_13_fu_1154_p4 <= add_ln230_1_fu_1148_p2(31 downto 7);
    tmp_14_fu_1208_p4 <= add_ln231_fu_1202_p2(17 downto 1);
    tmp_15_fu_1228_p4 <= add_ln231_1_fu_1222_p2(31 downto 7);
    tmp_16_fu_1282_p4 <= add_ln232_fu_1276_p2(17 downto 1);
    tmp_17_fu_1302_p4 <= add_ln232_1_fu_1296_p2(31 downto 7);
    tmp_18_fu_1356_p4 <= add_ln233_fu_1350_p2(17 downto 1);
    tmp_19_fu_1376_p4 <= add_ln233_1_fu_1370_p2(31 downto 7);
    tmp_1_fu_644_p4 <= s_1_fu_346_p2(16 downto 7);
    tmp_20_fu_1430_p4 <= add_ln234_fu_1424_p2(17 downto 1);
    tmp_21_fu_1450_p4 <= add_ln234_1_fu_1444_p2(31 downto 7);
    tmp_22_fu_1504_p4 <= add_ln235_fu_1498_p2(17 downto 1);
    tmp_23_fu_1524_p4 <= add_ln235_1_fu_1518_p2(31 downto 7);
    tmp_2_fu_692_p4 <= s_2_fu_386_p2(16 downto 7);
    tmp_3_fu_740_p4 <= s_3_fu_426_p2(16 downto 7);
    tmp_4_fu_788_p4 <= s_4_fu_466_p2(16 downto 7);
    tmp_5_fu_836_p4 <= s_5_fu_506_p2(16 downto 7);
    tmp_6_fu_884_p4 <= s_6_fu_546_p2(16 downto 7);
    tmp_7_fu_932_p4 <= s_7_fu_586_p2(16 downto 7);
    tmp_8_fu_986_p4 <= add_ln228_fu_980_p2(17 downto 1);
    tmp_9_fu_1006_p4 <= add_ln228_1_fu_1000_p2(31 downto 7);
    tmp_fu_596_p4 <= s_fu_316_p2(16 downto 7);
    trunc_ln11_10_fu_1176_p1 <= add_ln230_1_fu_1148_p2(8 - 1 downto 0);
    trunc_ln11_11_fu_1250_p1 <= add_ln231_1_fu_1222_p2(8 - 1 downto 0);
    trunc_ln11_12_fu_1324_p1 <= add_ln232_1_fu_1296_p2(8 - 1 downto 0);
    trunc_ln11_13_fu_1398_p1 <= add_ln233_1_fu_1370_p2(8 - 1 downto 0);
    trunc_ln11_14_fu_1472_p1 <= add_ln234_1_fu_1444_p2(8 - 1 downto 0);
    trunc_ln11_15_fu_1546_p1 <= add_ln235_1_fu_1518_p2(8 - 1 downto 0);
    trunc_ln11_1_fu_666_p1 <= s_1_fu_346_p2(8 - 1 downto 0);
    trunc_ln11_2_fu_714_p1 <= s_2_fu_386_p2(8 - 1 downto 0);
    trunc_ln11_3_fu_762_p1 <= s_3_fu_426_p2(8 - 1 downto 0);
    trunc_ln11_4_fu_810_p1 <= s_4_fu_466_p2(8 - 1 downto 0);
    trunc_ln11_5_fu_858_p1 <= s_5_fu_506_p2(8 - 1 downto 0);
    trunc_ln11_6_fu_906_p1 <= s_6_fu_546_p2(8 - 1 downto 0);
    trunc_ln11_7_fu_954_p1 <= s_7_fu_586_p2(8 - 1 downto 0);
    trunc_ln11_8_fu_1028_p1 <= add_ln228_1_fu_1000_p2(8 - 1 downto 0);
    trunc_ln11_9_fu_1102_p1 <= add_ln229_1_fu_1074_p2(8 - 1 downto 0);
    trunc_ln11_fu_618_p1 <= s_fu_316_p2(8 - 1 downto 0);
    trunc_ln1_fu_332_p4 <= add_ln211_fu_326_p2(17 downto 2);
    trunc_ln2_fu_372_p4 <= add_ln212_1_fu_366_p2(17 downto 2);
    trunc_ln3_fu_412_p4 <= add_ln213_1_fu_406_p2(17 downto 2);
    trunc_ln4_fu_452_p4 <= add_ln214_1_fu_446_p2(17 downto 2);
    trunc_ln5_fu_492_p4 <= add_ln215_1_fu_486_p2(17 downto 2);
    trunc_ln6_fu_532_p4 <= add_ln216_1_fu_526_p2(17 downto 2);
    trunc_ln7_fu_572_p4 <= add_ln217_1_fu_566_p2(17 downto 2);
    trunc_ln_fu_302_p4 <= add_ln210_1_fu_296_p2(17 downto 2);
end behav;
