// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="HW_dwt53_inverse_HW_dwt53_inverse,hls_ip_2024_2,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcku5p-ffvb676-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.627250,HLS_SYN_LAT=1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=2,HLS_SYN_LUT=2286,HLS_VERSION=2024_2}" *)

module HW_dwt53_inverse (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        low_03,
        low_47,
        high_03,
        high_47,
        p_out_0,
        p_out_0_ap_vld,
        p_out_1,
        p_out_1_ap_vld
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] low_03;
input  [63:0] low_47;
input  [63:0] high_03;
input  [63:0] high_47;
output  [63:0] p_out_0;
output   p_out_0_ap_vld;
output  [63:0] p_out_1;
output   p_out_1_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_out_0_ap_vld;
reg p_out_1_ap_vld;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    call_ret_HW_dwt53_inverse_core_fu_94_ap_ready;
wire   [15:0] call_ret_HW_dwt53_inverse_core_fu_94_low_read;
wire   [15:0] call_ret_HW_dwt53_inverse_core_fu_94_low_read_23;
wire   [15:0] call_ret_HW_dwt53_inverse_core_fu_94_low_read_24;
wire   [15:0] call_ret_HW_dwt53_inverse_core_fu_94_low_read_25;
wire   [15:0] call_ret_HW_dwt53_inverse_core_fu_94_low_read_26;
wire   [15:0] call_ret_HW_dwt53_inverse_core_fu_94_low_read_27;
wire   [15:0] call_ret_HW_dwt53_inverse_core_fu_94_low_read_28;
wire   [15:0] call_ret_HW_dwt53_inverse_core_fu_94_low_read_29;
wire   [15:0] call_ret_HW_dwt53_inverse_core_fu_94_high_read;
wire   [15:0] call_ret_HW_dwt53_inverse_core_fu_94_high_read_23;
wire   [15:0] call_ret_HW_dwt53_inverse_core_fu_94_high_read_24;
wire   [15:0] call_ret_HW_dwt53_inverse_core_fu_94_high_read_25;
wire   [15:0] call_ret_HW_dwt53_inverse_core_fu_94_high_read_26;
wire   [15:0] call_ret_HW_dwt53_inverse_core_fu_94_high_read_27;
wire   [15:0] call_ret_HW_dwt53_inverse_core_fu_94_high_read_28;
wire   [15:0] call_ret_HW_dwt53_inverse_core_fu_94_high_read_29;
wire   [7:0] call_ret_HW_dwt53_inverse_core_fu_94_ap_return_0;
wire   [7:0] call_ret_HW_dwt53_inverse_core_fu_94_ap_return_1;
wire   [7:0] call_ret_HW_dwt53_inverse_core_fu_94_ap_return_2;
wire   [7:0] call_ret_HW_dwt53_inverse_core_fu_94_ap_return_3;
wire   [7:0] call_ret_HW_dwt53_inverse_core_fu_94_ap_return_4;
wire   [7:0] call_ret_HW_dwt53_inverse_core_fu_94_ap_return_5;
wire   [7:0] call_ret_HW_dwt53_inverse_core_fu_94_ap_return_6;
wire   [7:0] call_ret_HW_dwt53_inverse_core_fu_94_ap_return_7;
wire   [7:0] call_ret_HW_dwt53_inverse_core_fu_94_ap_return_8;
wire   [7:0] call_ret_HW_dwt53_inverse_core_fu_94_ap_return_9;
wire   [7:0] call_ret_HW_dwt53_inverse_core_fu_94_ap_return_10;
wire   [7:0] call_ret_HW_dwt53_inverse_core_fu_94_ap_return_11;
wire   [7:0] call_ret_HW_dwt53_inverse_core_fu_94_ap_return_12;
wire   [7:0] call_ret_HW_dwt53_inverse_core_fu_94_ap_return_13;
wire   [7:0] call_ret_HW_dwt53_inverse_core_fu_94_ap_return_14;
wire   [7:0] call_ret_HW_dwt53_inverse_core_fu_94_ap_return_15;
wire    ap_CS_fsm_state2;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
end

HW_dwt53_inverse_HW_dwt53_inverse_core call_ret_HW_dwt53_inverse_core_fu_94(
    .ap_ready(call_ret_HW_dwt53_inverse_core_fu_94_ap_ready),
    .low_read(call_ret_HW_dwt53_inverse_core_fu_94_low_read),
    .low_read_23(call_ret_HW_dwt53_inverse_core_fu_94_low_read_23),
    .low_read_24(call_ret_HW_dwt53_inverse_core_fu_94_low_read_24),
    .low_read_25(call_ret_HW_dwt53_inverse_core_fu_94_low_read_25),
    .low_read_26(call_ret_HW_dwt53_inverse_core_fu_94_low_read_26),
    .low_read_27(call_ret_HW_dwt53_inverse_core_fu_94_low_read_27),
    .low_read_28(call_ret_HW_dwt53_inverse_core_fu_94_low_read_28),
    .low_read_29(call_ret_HW_dwt53_inverse_core_fu_94_low_read_29),
    .high_read(call_ret_HW_dwt53_inverse_core_fu_94_high_read),
    .high_read_23(call_ret_HW_dwt53_inverse_core_fu_94_high_read_23),
    .high_read_24(call_ret_HW_dwt53_inverse_core_fu_94_high_read_24),
    .high_read_25(call_ret_HW_dwt53_inverse_core_fu_94_high_read_25),
    .high_read_26(call_ret_HW_dwt53_inverse_core_fu_94_high_read_26),
    .high_read_27(call_ret_HW_dwt53_inverse_core_fu_94_high_read_27),
    .high_read_28(call_ret_HW_dwt53_inverse_core_fu_94_high_read_28),
    .high_read_29(call_ret_HW_dwt53_inverse_core_fu_94_high_read_29),
    .ap_return_0(call_ret_HW_dwt53_inverse_core_fu_94_ap_return_0),
    .ap_return_1(call_ret_HW_dwt53_inverse_core_fu_94_ap_return_1),
    .ap_return_2(call_ret_HW_dwt53_inverse_core_fu_94_ap_return_2),
    .ap_return_3(call_ret_HW_dwt53_inverse_core_fu_94_ap_return_3),
    .ap_return_4(call_ret_HW_dwt53_inverse_core_fu_94_ap_return_4),
    .ap_return_5(call_ret_HW_dwt53_inverse_core_fu_94_ap_return_5),
    .ap_return_6(call_ret_HW_dwt53_inverse_core_fu_94_ap_return_6),
    .ap_return_7(call_ret_HW_dwt53_inverse_core_fu_94_ap_return_7),
    .ap_return_8(call_ret_HW_dwt53_inverse_core_fu_94_ap_return_8),
    .ap_return_9(call_ret_HW_dwt53_inverse_core_fu_94_ap_return_9),
    .ap_return_10(call_ret_HW_dwt53_inverse_core_fu_94_ap_return_10),
    .ap_return_11(call_ret_HW_dwt53_inverse_core_fu_94_ap_return_11),
    .ap_return_12(call_ret_HW_dwt53_inverse_core_fu_94_ap_return_12),
    .ap_return_13(call_ret_HW_dwt53_inverse_core_fu_94_ap_return_13),
    .ap_return_14(call_ret_HW_dwt53_inverse_core_fu_94_ap_return_14),
    .ap_return_15(call_ret_HW_dwt53_inverse_core_fu_94_ap_return_15),
    .ap_rst(ap_rst)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_out_0_ap_vld = 1'b1;
    end else begin
        p_out_0_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_out_1_ap_vld = 1'b1;
    end else begin
        p_out_1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign call_ret_HW_dwt53_inverse_core_fu_94_high_read = {{high_03[63:48]}};

assign call_ret_HW_dwt53_inverse_core_fu_94_high_read_23 = {{high_03[47:32]}};

assign call_ret_HW_dwt53_inverse_core_fu_94_high_read_24 = {{high_03[31:16]}};

assign call_ret_HW_dwt53_inverse_core_fu_94_high_read_25 = high_03[15:0];

assign call_ret_HW_dwt53_inverse_core_fu_94_high_read_26 = {{high_47[63:48]}};

assign call_ret_HW_dwt53_inverse_core_fu_94_high_read_27 = {{high_47[47:32]}};

assign call_ret_HW_dwt53_inverse_core_fu_94_high_read_28 = {{high_47[31:16]}};

assign call_ret_HW_dwt53_inverse_core_fu_94_high_read_29 = high_47[15:0];

assign call_ret_HW_dwt53_inverse_core_fu_94_low_read = {{low_03[63:48]}};

assign call_ret_HW_dwt53_inverse_core_fu_94_low_read_23 = {{low_03[47:32]}};

assign call_ret_HW_dwt53_inverse_core_fu_94_low_read_24 = {{low_03[31:16]}};

assign call_ret_HW_dwt53_inverse_core_fu_94_low_read_25 = low_03[15:0];

assign call_ret_HW_dwt53_inverse_core_fu_94_low_read_26 = {{low_47[63:48]}};

assign call_ret_HW_dwt53_inverse_core_fu_94_low_read_27 = {{low_47[47:32]}};

assign call_ret_HW_dwt53_inverse_core_fu_94_low_read_28 = {{low_47[31:16]}};

assign call_ret_HW_dwt53_inverse_core_fu_94_low_read_29 = low_47[15:0];

assign p_out_0 = {{{{{{{{call_ret_HW_dwt53_inverse_core_fu_94_ap_return_0}, {call_ret_HW_dwt53_inverse_core_fu_94_ap_return_1}}, {call_ret_HW_dwt53_inverse_core_fu_94_ap_return_2}}, {call_ret_HW_dwt53_inverse_core_fu_94_ap_return_3}}, {call_ret_HW_dwt53_inverse_core_fu_94_ap_return_4}}, {call_ret_HW_dwt53_inverse_core_fu_94_ap_return_5}}, {call_ret_HW_dwt53_inverse_core_fu_94_ap_return_6}}, {call_ret_HW_dwt53_inverse_core_fu_94_ap_return_7}};

assign p_out_1 = {{{{{{{{call_ret_HW_dwt53_inverse_core_fu_94_ap_return_8}, {call_ret_HW_dwt53_inverse_core_fu_94_ap_return_9}}, {call_ret_HW_dwt53_inverse_core_fu_94_ap_return_10}}, {call_ret_HW_dwt53_inverse_core_fu_94_ap_return_11}}, {call_ret_HW_dwt53_inverse_core_fu_94_ap_return_12}}, {call_ret_HW_dwt53_inverse_core_fu_94_ap_return_13}}, {call_ret_HW_dwt53_inverse_core_fu_94_ap_return_14}}, {call_ret_HW_dwt53_inverse_core_fu_94_ap_return_15}};

endmodule //HW_dwt53_inverse
