-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity HW_dwt53_forward is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    op1 : IN STD_LOGIC_VECTOR (63 downto 0);
    op2 : IN STD_LOGIC_VECTOR (63 downto 0);
    p_low_03 : OUT STD_LOGIC_VECTOR (63 downto 0);
    p_low_03_ap_vld : OUT STD_LOGIC;
    p_low_47 : OUT STD_LOGIC_VECTOR (63 downto 0);
    p_low_47_ap_vld : OUT STD_LOGIC;
    p_high_03 : OUT STD_LOGIC_VECTOR (63 downto 0);
    p_high_03_ap_vld : OUT STD_LOGIC;
    p_high_47 : OUT STD_LOGIC_VECTOR (63 downto 0);
    p_high_47_ap_vld : OUT STD_LOGIC );
end;


architecture behav of HW_dwt53_forward is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "HW_dwt53_forward_HW_dwt53_forward,hls_ip_2024_2,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcku5p-ffvb676-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.869000,HLS_SYN_LAT=1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=2,HLS_SYN_LUT=717,HLS_VERSION=2024_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_38 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_37 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110111";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv10_2 : STD_LOGIC_VECTOR (9 downto 0) := "0000000010";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal inputs_fu_124_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal inputs_17_fu_144_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal inputs_19_fu_164_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal inputs_21_fu_184_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal inputs_23_fu_198_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal inputs_25_fu_218_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal inputs_27_fu_238_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal inputs_29_fu_258_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal inputs_16_fu_134_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal inputs_18_fu_154_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal inputs_20_fu_174_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal inputs_22_fu_194_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal inputs_24_fu_208_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal inputs_26_fu_228_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal inputs_28_fu_248_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal inputs_30_fu_268_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln44_1_fu_276_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln44_fu_272_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln65_fu_336_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln_fu_342_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln45_fu_304_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln65_fu_352_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal d_fu_356_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln44_2_fu_280_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln66_fu_366_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln1_fu_372_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln45_1_fu_308_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln66_fu_382_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal d_16_fu_386_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln44_3_fu_284_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln67_fu_396_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln2_fu_402_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln45_2_fu_312_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln67_fu_412_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal d_10_fu_416_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln44_4_fu_288_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln68_fu_430_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln3_fu_436_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln45_3_fu_316_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln68_fu_446_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal d_17_fu_450_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln44_5_fu_292_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln69_fu_464_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln4_fu_470_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln45_4_fu_320_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln69_fu_480_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal d_18_fu_484_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln44_6_fu_296_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln70_fu_498_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln5_fu_504_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln45_5_fu_324_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln70_fu_514_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal d_19_fu_518_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln44_7_fu_300_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln71_fu_532_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln6_fu_538_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln45_6_fu_328_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln71_fu_548_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal d_14_fu_552_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln72_fu_566_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln7_fu_572_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln45_7_fu_332_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln72_fu_582_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal d_20_fu_586_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln45_8_fu_362_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln74_fu_600_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln45_21_fu_596_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln74_1_fu_606_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln74_1_fu_610_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_fu_620_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln45_9_fu_392_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln75_fu_634_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_1_fu_644_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln45_11_fu_426_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln76_fu_658_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln76_1_fu_664_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln76_1_fu_668_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_2_fu_678_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln45_13_fu_460_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln77_fu_692_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln77_1_fu_698_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln45_10_fu_422_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln77_1_fu_702_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_3_fu_712_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln45_15_fu_494_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln78_fu_726_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln78_1_fu_732_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln45_12_fu_456_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln78_1_fu_736_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_4_fu_746_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln45_17_fu_528_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln79_fu_760_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln79_1_fu_766_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln45_14_fu_490_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln79_1_fu_770_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_5_fu_780_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln45_19_fu_562_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln80_fu_794_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln80_1_fu_800_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln45_16_fu_524_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln80_1_fu_804_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_6_fu_814_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln45_20_fu_592_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln81_fu_828_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln81_1_fu_834_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln45_18_fu_558_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln81_1_fu_838_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_7_fu_848_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln74_2_fu_630_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln74_fu_616_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln75_1_fu_654_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln75_fu_640_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln76_2_fu_688_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln76_fu_674_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln77_2_fu_722_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln77_fu_708_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln78_2_fu_756_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln78_fu_742_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln79_2_fu_790_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln79_fu_776_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln80_2_fu_824_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln80_fu_810_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln81_2_fu_858_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln81_fu_844_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal low_fu_862_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal low_1_fu_868_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal low_2_fu_874_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal low_3_fu_880_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal low_4_fu_886_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal low_5_fu_892_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal low_6_fu_898_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal low_7_fu_904_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln93_fu_910_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln150_fu_952_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln95_fu_914_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal or_ln2_fu_956_p5 : STD_LOGIC_VECTOR (56 downto 0);
    signal sext_ln97_fu_918_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln157_fu_973_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln99_fu_922_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal or_ln3_fu_977_p5 : STD_LOGIC_VECTOR (56 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    add_ln65_fu_336_p2 <= std_logic_vector(signed(sext_ln44_1_fu_276_p1) + signed(sext_ln44_fu_272_p1));
    add_ln66_fu_366_p2 <= std_logic_vector(signed(sext_ln44_2_fu_280_p1) + signed(sext_ln44_1_fu_276_p1));
    add_ln67_fu_396_p2 <= std_logic_vector(signed(sext_ln44_3_fu_284_p1) + signed(sext_ln44_2_fu_280_p1));
    add_ln68_fu_430_p2 <= std_logic_vector(signed(sext_ln44_4_fu_288_p1) + signed(sext_ln44_3_fu_284_p1));
    add_ln69_fu_464_p2 <= std_logic_vector(signed(sext_ln44_5_fu_292_p1) + signed(sext_ln44_4_fu_288_p1));
    add_ln70_fu_498_p2 <= std_logic_vector(signed(sext_ln44_6_fu_296_p1) + signed(sext_ln44_5_fu_292_p1));
    add_ln71_fu_532_p2 <= std_logic_vector(signed(sext_ln44_7_fu_300_p1) + signed(sext_ln44_6_fu_296_p1));
    add_ln72_fu_566_p2 <= std_logic_vector(signed(sext_ln44_7_fu_300_p1) + signed(sext_ln44_fu_272_p1));
    add_ln74_1_fu_610_p2 <= std_logic_vector(signed(sext_ln45_21_fu_596_p1) + signed(sext_ln74_1_fu_606_p1));
    add_ln74_fu_600_p2 <= std_logic_vector(signed(sext_ln45_8_fu_362_p1) + signed(ap_const_lv10_2));
    add_ln75_fu_634_p2 <= std_logic_vector(signed(sext_ln74_1_fu_606_p1) + signed(sext_ln45_9_fu_392_p1));
    add_ln76_1_fu_668_p2 <= std_logic_vector(signed(sext_ln76_1_fu_664_p1) + signed(sext_ln45_9_fu_392_p1));
    add_ln76_fu_658_p2 <= std_logic_vector(signed(sext_ln45_11_fu_426_p1) + signed(ap_const_lv10_2));
    add_ln77_1_fu_702_p2 <= std_logic_vector(signed(sext_ln77_1_fu_698_p1) + signed(sext_ln45_10_fu_422_p1));
    add_ln77_fu_692_p2 <= std_logic_vector(signed(sext_ln45_13_fu_460_p1) + signed(ap_const_lv10_2));
    add_ln78_1_fu_736_p2 <= std_logic_vector(signed(sext_ln78_1_fu_732_p1) + signed(sext_ln45_12_fu_456_p1));
    add_ln78_fu_726_p2 <= std_logic_vector(signed(sext_ln45_15_fu_494_p1) + signed(ap_const_lv10_2));
    add_ln79_1_fu_770_p2 <= std_logic_vector(signed(sext_ln79_1_fu_766_p1) + signed(sext_ln45_14_fu_490_p1));
    add_ln79_fu_760_p2 <= std_logic_vector(signed(sext_ln45_17_fu_528_p1) + signed(ap_const_lv10_2));
    add_ln80_1_fu_804_p2 <= std_logic_vector(signed(sext_ln80_1_fu_800_p1) + signed(sext_ln45_16_fu_524_p1));
    add_ln80_fu_794_p2 <= std_logic_vector(signed(sext_ln45_19_fu_562_p1) + signed(ap_const_lv10_2));
    add_ln81_1_fu_838_p2 <= std_logic_vector(signed(sext_ln81_1_fu_834_p1) + signed(sext_ln45_18_fu_558_p1));
    add_ln81_fu_828_p2 <= std_logic_vector(signed(sext_ln45_20_fu_592_p1) + signed(ap_const_lv10_2));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    d_10_fu_416_p2 <= std_logic_vector(signed(sext_ln45_2_fu_312_p1) - signed(sext_ln67_fu_412_p1));
    d_14_fu_552_p2 <= std_logic_vector(signed(sext_ln45_6_fu_328_p1) - signed(sext_ln71_fu_548_p1));
    d_16_fu_386_p2 <= std_logic_vector(signed(sext_ln45_1_fu_308_p1) - signed(sext_ln66_fu_382_p1));
    d_17_fu_450_p2 <= std_logic_vector(signed(sext_ln45_3_fu_316_p1) - signed(sext_ln68_fu_446_p1));
    d_18_fu_484_p2 <= std_logic_vector(signed(sext_ln45_4_fu_320_p1) - signed(sext_ln69_fu_480_p1));
    d_19_fu_518_p2 <= std_logic_vector(signed(sext_ln45_5_fu_324_p1) - signed(sext_ln70_fu_514_p1));
    d_20_fu_586_p2 <= std_logic_vector(signed(sext_ln45_7_fu_332_p1) - signed(sext_ln72_fu_582_p1));
    d_fu_356_p2 <= std_logic_vector(signed(sext_ln45_fu_304_p1) - signed(sext_ln65_fu_352_p1));
    inputs_16_fu_134_p4 <= op1(55 downto 48);
    inputs_17_fu_144_p4 <= op1(47 downto 40);
    inputs_18_fu_154_p4 <= op1(39 downto 32);
    inputs_19_fu_164_p4 <= op1(31 downto 24);
    inputs_20_fu_174_p4 <= op1(23 downto 16);
    inputs_21_fu_184_p4 <= op1(15 downto 8);
    inputs_22_fu_194_p1 <= op1(8 - 1 downto 0);
    inputs_23_fu_198_p4 <= op2(63 downto 56);
    inputs_24_fu_208_p4 <= op2(55 downto 48);
    inputs_25_fu_218_p4 <= op2(47 downto 40);
    inputs_26_fu_228_p4 <= op2(39 downto 32);
    inputs_27_fu_238_p4 <= op2(31 downto 24);
    inputs_28_fu_248_p4 <= op2(23 downto 16);
    inputs_29_fu_258_p4 <= op2(15 downto 8);
    inputs_30_fu_268_p1 <= op2(8 - 1 downto 0);
    inputs_fu_124_p4 <= op1(63 downto 56);
    low_1_fu_868_p2 <= std_logic_vector(signed(sext_ln75_1_fu_654_p1) + signed(sext_ln75_fu_640_p1));
    low_2_fu_874_p2 <= std_logic_vector(signed(sext_ln76_2_fu_688_p1) + signed(sext_ln76_fu_674_p1));
    low_3_fu_880_p2 <= std_logic_vector(signed(sext_ln77_2_fu_722_p1) + signed(sext_ln77_fu_708_p1));
    low_4_fu_886_p2 <= std_logic_vector(signed(sext_ln78_2_fu_756_p1) + signed(sext_ln78_fu_742_p1));
    low_5_fu_892_p2 <= std_logic_vector(signed(sext_ln79_2_fu_790_p1) + signed(sext_ln79_fu_776_p1));
    low_6_fu_898_p2 <= std_logic_vector(signed(sext_ln80_2_fu_824_p1) + signed(sext_ln80_fu_810_p1));
    low_7_fu_904_p2 <= std_logic_vector(signed(sext_ln81_2_fu_858_p1) + signed(sext_ln81_fu_844_p1));
    low_fu_862_p2 <= std_logic_vector(signed(sext_ln74_2_fu_630_p1) + signed(sext_ln74_fu_616_p1));
    or_ln2_fu_956_p5 <= (((d_fu_356_p2 & sext_ln93_fu_910_p1) & sext_ln150_fu_952_p1) & sext_ln95_fu_914_p1);
    or_ln3_fu_977_p5 <= (((d_18_fu_484_p2 & sext_ln97_fu_918_p1) & sext_ln157_fu_973_p1) & sext_ln99_fu_922_p1);
        p_high_03 <= std_logic_vector(IEEE.numeric_std.resize(signed(or_ln2_fu_956_p5),64));


    p_high_03_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_high_03_ap_vld <= ap_const_logic_1;
        else 
            p_high_03_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

        p_high_47 <= std_logic_vector(IEEE.numeric_std.resize(signed(or_ln3_fu_977_p5),64));


    p_high_47_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_high_47_ap_vld <= ap_const_logic_1;
        else 
            p_high_47_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_low_03 <= (((low_fu_862_p2 & low_1_fu_868_p2) & low_2_fu_874_p2) & low_3_fu_880_p2);

    p_low_03_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_low_03_ap_vld <= ap_const_logic_1;
        else 
            p_low_03_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_low_47 <= (((low_4_fu_886_p2 & low_5_fu_892_p2) & low_6_fu_898_p2) & low_7_fu_904_p2);

    p_low_47_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_low_47_ap_vld <= ap_const_logic_1;
        else 
            p_low_47_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

        sext_ln150_fu_952_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(d_10_fu_416_p2),16));

        sext_ln157_fu_973_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(d_14_fu_552_p2),16));

        sext_ln44_1_fu_276_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(inputs_17_fu_144_p4),9));

        sext_ln44_2_fu_280_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(inputs_19_fu_164_p4),9));

        sext_ln44_3_fu_284_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(inputs_21_fu_184_p4),9));

        sext_ln44_4_fu_288_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(inputs_23_fu_198_p4),9));

        sext_ln44_5_fu_292_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(inputs_25_fu_218_p4),9));

        sext_ln44_6_fu_296_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(inputs_27_fu_238_p4),9));

        sext_ln44_7_fu_300_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(inputs_29_fu_258_p4),9));

        sext_ln44_fu_272_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(inputs_fu_124_p4),9));

        sext_ln45_10_fu_422_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(d_10_fu_416_p2),11));

        sext_ln45_11_fu_426_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(d_10_fu_416_p2),10));

        sext_ln45_12_fu_456_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(d_17_fu_450_p2),11));

        sext_ln45_13_fu_460_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(d_17_fu_450_p2),10));

        sext_ln45_14_fu_490_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(d_18_fu_484_p2),11));

        sext_ln45_15_fu_494_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(d_18_fu_484_p2),10));

        sext_ln45_16_fu_524_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(d_19_fu_518_p2),11));

        sext_ln45_17_fu_528_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(d_19_fu_518_p2),10));

        sext_ln45_18_fu_558_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(d_14_fu_552_p2),11));

        sext_ln45_19_fu_562_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(d_14_fu_552_p2),10));

        sext_ln45_1_fu_308_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(inputs_18_fu_154_p4),9));

        sext_ln45_20_fu_592_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(d_20_fu_586_p2),10));

        sext_ln45_21_fu_596_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(d_20_fu_586_p2),11));

        sext_ln45_2_fu_312_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(inputs_20_fu_174_p4),9));

        sext_ln45_3_fu_316_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(inputs_22_fu_194_p1),9));

        sext_ln45_4_fu_320_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(inputs_24_fu_208_p4),9));

        sext_ln45_5_fu_324_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(inputs_26_fu_228_p4),9));

        sext_ln45_6_fu_328_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(inputs_28_fu_248_p4),9));

        sext_ln45_7_fu_332_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(inputs_30_fu_268_p1),9));

        sext_ln45_8_fu_362_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(d_fu_356_p2),10));

        sext_ln45_9_fu_392_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(d_16_fu_386_p2),11));

        sext_ln45_fu_304_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(inputs_16_fu_134_p4),9));

        sext_ln65_fu_352_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln_fu_342_p4),9));

        sext_ln66_fu_382_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln1_fu_372_p4),9));

        sext_ln67_fu_412_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln2_fu_402_p4),9));

        sext_ln68_fu_446_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln3_fu_436_p4),9));

        sext_ln69_fu_480_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln4_fu_470_p4),9));

        sext_ln70_fu_514_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln5_fu_504_p4),9));

        sext_ln71_fu_548_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln6_fu_538_p4),9));

        sext_ln72_fu_582_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln7_fu_572_p4),9));

        sext_ln74_1_fu_606_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln74_fu_600_p2),11));

        sext_ln74_2_fu_630_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_fu_620_p4),16));

        sext_ln74_fu_616_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(inputs_fu_124_p4),16));

        sext_ln75_1_fu_654_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_1_fu_644_p4),16));

        sext_ln75_fu_640_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(inputs_17_fu_144_p4),16));

        sext_ln76_1_fu_664_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln76_fu_658_p2),11));

        sext_ln76_2_fu_688_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_2_fu_678_p4),16));

        sext_ln76_fu_674_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(inputs_19_fu_164_p4),16));

        sext_ln77_1_fu_698_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln77_fu_692_p2),11));

        sext_ln77_2_fu_722_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_3_fu_712_p4),16));

        sext_ln77_fu_708_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(inputs_21_fu_184_p4),16));

        sext_ln78_1_fu_732_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln78_fu_726_p2),11));

        sext_ln78_2_fu_756_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_4_fu_746_p4),16));

        sext_ln78_fu_742_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(inputs_23_fu_198_p4),16));

        sext_ln79_1_fu_766_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln79_fu_760_p2),11));

        sext_ln79_2_fu_790_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_5_fu_780_p4),16));

        sext_ln79_fu_776_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(inputs_25_fu_218_p4),16));

        sext_ln80_1_fu_800_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln80_fu_794_p2),11));

        sext_ln80_2_fu_824_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_6_fu_814_p4),16));

        sext_ln80_fu_810_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(inputs_27_fu_238_p4),16));

        sext_ln81_1_fu_834_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln81_fu_828_p2),11));

        sext_ln81_2_fu_858_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_7_fu_848_p4),16));

        sext_ln81_fu_844_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(inputs_29_fu_258_p4),16));

        sext_ln93_fu_910_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(d_16_fu_386_p2),16));

        sext_ln95_fu_914_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(d_17_fu_450_p2),16));

        sext_ln97_fu_918_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(d_19_fu_518_p2),16));

        sext_ln99_fu_922_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(d_20_fu_586_p2),16));

    tmp_1_fu_644_p4 <= add_ln75_fu_634_p2(10 downto 2);
    tmp_2_fu_678_p4 <= add_ln76_1_fu_668_p2(10 downto 2);
    tmp_3_fu_712_p4 <= add_ln77_1_fu_702_p2(10 downto 2);
    tmp_4_fu_746_p4 <= add_ln78_1_fu_736_p2(10 downto 2);
    tmp_5_fu_780_p4 <= add_ln79_1_fu_770_p2(10 downto 2);
    tmp_6_fu_814_p4 <= add_ln80_1_fu_804_p2(10 downto 2);
    tmp_7_fu_848_p4 <= add_ln81_1_fu_838_p2(10 downto 2);
    tmp_fu_620_p4 <= add_ln74_1_fu_610_p2(10 downto 2);
    trunc_ln1_fu_372_p4 <= add_ln66_fu_366_p2(8 downto 1);
    trunc_ln2_fu_402_p4 <= add_ln67_fu_396_p2(8 downto 1);
    trunc_ln3_fu_436_p4 <= add_ln68_fu_430_p2(8 downto 1);
    trunc_ln4_fu_470_p4 <= add_ln69_fu_464_p2(8 downto 1);
    trunc_ln5_fu_504_p4 <= add_ln70_fu_498_p2(8 downto 1);
    trunc_ln6_fu_538_p4 <= add_ln71_fu_532_p2(8 downto 1);
    trunc_ln7_fu_572_p4 <= add_ln72_fu_566_p2(8 downto 1);
    trunc_ln_fu_342_p4 <= add_ln65_fu_336_p2(8 downto 1);
end behav;
