// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="HW_dwt_db8_int16_HW_dwt_db8_int16,hls_ip_2024_2,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcku5p-ffvb676-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.631563,HLS_SYN_LAT=5,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1072,HLS_SYN_LUT=5198,HLS_VERSION=2024_2}" *)

module HW_dwt_db8_int16 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        op1,
        op2,
        p_low_03,
        p_low_03_ap_vld,
        p_low_47,
        p_low_47_ap_vld,
        p_high_03,
        p_high_03_ap_vld,
        p_high_47,
        p_high_47_ap_vld
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] op1;
input  [63:0] op2;
output  [63:0] p_low_03;
output   p_low_03_ap_vld;
output  [63:0] p_low_47;
output   p_low_47_ap_vld;
output  [63:0] p_high_03;
output   p_high_03_ap_vld;
output  [63:0] p_high_47;
output   p_high_47_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_low_03_ap_vld;
reg p_low_47_ap_vld;
reg p_high_03_ap_vld;
reg p_high_47_ap_vld;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [7:0] inputs_reg_406;
reg   [7:0] inputs_1_reg_411;
reg   [7:0] inputs_2_reg_416;
reg   [7:0] inputs_3_reg_421;
reg   [7:0] inputs_4_reg_426;
reg   [7:0] inputs_5_reg_431;
reg   [7:0] inputs_6_reg_436;
wire   [7:0] inputs_13_fu_203_p1;
reg   [7:0] inputs_13_reg_441;
reg   [7:0] inputs_8_reg_446;
reg   [7:0] inputs_9_reg_451;
reg   [7:0] inputs_14_reg_456;
reg   [7:0] inputs_7_reg_461;
reg   [7:0] inputs_10_reg_466;
reg   [7:0] inputs_11_reg_471;
reg   [7:0] inputs_12_reg_476;
wire   [7:0] inputs_15_fu_285_p1;
reg   [7:0] inputs_15_reg_481;
wire    grp_HW_dwt_db8_int16_core_fu_106_ap_start;
wire    grp_HW_dwt_db8_int16_core_fu_106_ap_done;
wire    grp_HW_dwt_db8_int16_core_fu_106_ap_idle;
wire    grp_HW_dwt_db8_int16_core_fu_106_ap_ready;
wire   [15:0] grp_HW_dwt_db8_int16_core_fu_106_ap_return_0;
wire   [15:0] grp_HW_dwt_db8_int16_core_fu_106_ap_return_1;
wire   [15:0] grp_HW_dwt_db8_int16_core_fu_106_ap_return_2;
wire   [15:0] grp_HW_dwt_db8_int16_core_fu_106_ap_return_3;
wire   [15:0] grp_HW_dwt_db8_int16_core_fu_106_ap_return_4;
wire   [15:0] grp_HW_dwt_db8_int16_core_fu_106_ap_return_5;
wire   [15:0] grp_HW_dwt_db8_int16_core_fu_106_ap_return_6;
wire   [15:0] grp_HW_dwt_db8_int16_core_fu_106_ap_return_7;
wire   [15:0] grp_HW_dwt_db8_int16_core_fu_106_ap_return_8;
wire   [15:0] grp_HW_dwt_db8_int16_core_fu_106_ap_return_9;
wire   [15:0] grp_HW_dwt_db8_int16_core_fu_106_ap_return_10;
wire   [15:0] grp_HW_dwt_db8_int16_core_fu_106_ap_return_11;
wire   [15:0] grp_HW_dwt_db8_int16_core_fu_106_ap_return_12;
wire   [15:0] grp_HW_dwt_db8_int16_core_fu_106_ap_return_13;
wire   [15:0] grp_HW_dwt_db8_int16_core_fu_106_ap_return_14;
wire   [15:0] grp_HW_dwt_db8_int16_core_fu_106_ap_return_15;
reg    grp_HW_dwt_db8_int16_core_fu_106_ap_start_reg;
wire    ap_CS_fsm_state2;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 grp_HW_dwt_db8_int16_core_fu_106_ap_start_reg = 1'b0;
end

HW_dwt_db8_int16_HW_dwt_db8_int16_core grp_HW_dwt_db8_int16_core_fu_106(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_HW_dwt_db8_int16_core_fu_106_ap_start),
    .ap_done(grp_HW_dwt_db8_int16_core_fu_106_ap_done),
    .ap_idle(grp_HW_dwt_db8_int16_core_fu_106_ap_idle),
    .ap_ready(grp_HW_dwt_db8_int16_core_fu_106_ap_ready),
    .input_read(inputs_reg_406),
    .input_read_47(inputs_1_reg_411),
    .input_read_48(inputs_2_reg_416),
    .input_read_49(inputs_3_reg_421),
    .input_read_50(inputs_4_reg_426),
    .input_read_51(inputs_5_reg_431),
    .input_read_52(inputs_6_reg_436),
    .input_read_53(inputs_13_reg_441),
    .input_read_54(inputs_8_reg_446),
    .input_read_55(inputs_9_reg_451),
    .input_read_56(inputs_14_reg_456),
    .input_read_57(inputs_7_reg_461),
    .input_read_58(inputs_10_reg_466),
    .input_read_59(inputs_11_reg_471),
    .input_read_60(inputs_12_reg_476),
    .input_read_61(inputs_15_reg_481),
    .ap_return_0(grp_HW_dwt_db8_int16_core_fu_106_ap_return_0),
    .ap_return_1(grp_HW_dwt_db8_int16_core_fu_106_ap_return_1),
    .ap_return_2(grp_HW_dwt_db8_int16_core_fu_106_ap_return_2),
    .ap_return_3(grp_HW_dwt_db8_int16_core_fu_106_ap_return_3),
    .ap_return_4(grp_HW_dwt_db8_int16_core_fu_106_ap_return_4),
    .ap_return_5(grp_HW_dwt_db8_int16_core_fu_106_ap_return_5),
    .ap_return_6(grp_HW_dwt_db8_int16_core_fu_106_ap_return_6),
    .ap_return_7(grp_HW_dwt_db8_int16_core_fu_106_ap_return_7),
    .ap_return_8(grp_HW_dwt_db8_int16_core_fu_106_ap_return_8),
    .ap_return_9(grp_HW_dwt_db8_int16_core_fu_106_ap_return_9),
    .ap_return_10(grp_HW_dwt_db8_int16_core_fu_106_ap_return_10),
    .ap_return_11(grp_HW_dwt_db8_int16_core_fu_106_ap_return_11),
    .ap_return_12(grp_HW_dwt_db8_int16_core_fu_106_ap_return_12),
    .ap_return_13(grp_HW_dwt_db8_int16_core_fu_106_ap_return_13),
    .ap_return_14(grp_HW_dwt_db8_int16_core_fu_106_ap_return_14),
    .ap_return_15(grp_HW_dwt_db8_int16_core_fu_106_ap_return_15)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_HW_dwt_db8_int16_core_fu_106_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_HW_dwt_db8_int16_core_fu_106_ap_start_reg <= 1'b1;
        end else if ((grp_HW_dwt_db8_int16_core_fu_106_ap_ready == 1'b1)) begin
            grp_HW_dwt_db8_int16_core_fu_106_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        inputs_10_reg_466 <= {{op2[31:24]}};
        inputs_11_reg_471 <= {{op2[23:16]}};
        inputs_12_reg_476 <= {{op2[15:8]}};
        inputs_13_reg_441 <= inputs_13_fu_203_p1;
        inputs_14_reg_456 <= {{op2[47:40]}};
        inputs_15_reg_481 <= inputs_15_fu_285_p1;
        inputs_1_reg_411 <= {{op1[55:48]}};
        inputs_2_reg_416 <= {{op1[47:40]}};
        inputs_3_reg_421 <= {{op1[39:32]}};
        inputs_4_reg_426 <= {{op1[31:24]}};
        inputs_5_reg_431 <= {{op1[23:16]}};
        inputs_6_reg_436 <= {{op1[15:8]}};
        inputs_7_reg_461 <= {{op2[39:32]}};
        inputs_8_reg_446 <= {{op2[63:56]}};
        inputs_9_reg_451 <= {{op2[55:48]}};
        inputs_reg_406 <= {{op1[63:56]}};
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_HW_dwt_db8_int16_core_fu_106_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_HW_dwt_db8_int16_core_fu_106_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_HW_dwt_db8_int16_core_fu_106_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((grp_HW_dwt_db8_int16_core_fu_106_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        p_high_03_ap_vld = 1'b1;
    end else begin
        p_high_03_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_HW_dwt_db8_int16_core_fu_106_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        p_high_47_ap_vld = 1'b1;
    end else begin
        p_high_47_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_HW_dwt_db8_int16_core_fu_106_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        p_low_03_ap_vld = 1'b1;
    end else begin
        p_low_03_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_HW_dwt_db8_int16_core_fu_106_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        p_low_47_ap_vld = 1'b1;
    end else begin
        p_low_47_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_HW_dwt_db8_int16_core_fu_106_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign grp_HW_dwt_db8_int16_core_fu_106_ap_start = grp_HW_dwt_db8_int16_core_fu_106_ap_start_reg;

assign inputs_13_fu_203_p1 = op1[7:0];

assign inputs_15_fu_285_p1 = op2[7:0];

assign p_high_03 = {{{{grp_HW_dwt_db8_int16_core_fu_106_ap_return_8}, {grp_HW_dwt_db8_int16_core_fu_106_ap_return_9}}, {grp_HW_dwt_db8_int16_core_fu_106_ap_return_10}}, {grp_HW_dwt_db8_int16_core_fu_106_ap_return_11}};

assign p_high_47 = {{{{grp_HW_dwt_db8_int16_core_fu_106_ap_return_12}, {grp_HW_dwt_db8_int16_core_fu_106_ap_return_13}}, {grp_HW_dwt_db8_int16_core_fu_106_ap_return_14}}, {grp_HW_dwt_db8_int16_core_fu_106_ap_return_15}};

assign p_low_03 = {{{{grp_HW_dwt_db8_int16_core_fu_106_ap_return_0}, {grp_HW_dwt_db8_int16_core_fu_106_ap_return_1}}, {grp_HW_dwt_db8_int16_core_fu_106_ap_return_2}}, {grp_HW_dwt_db8_int16_core_fu_106_ap_return_3}};

assign p_low_47 = {{{{grp_HW_dwt_db8_int16_core_fu_106_ap_return_4}, {grp_HW_dwt_db8_int16_core_fu_106_ap_return_5}}, {grp_HW_dwt_db8_int16_core_fu_106_ap_return_6}}, {grp_HW_dwt_db8_int16_core_fu_106_ap_return_7}};

endmodule //HW_dwt_db8_int16
