// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="HW_dwt53_forward_HW_dwt53_forward,hls_ip_2024_2,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcku5p-ffvb676-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.869000,HLS_SYN_LAT=1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=2,HLS_SYN_LUT=717,HLS_VERSION=2024_2}" *)

module HW_dwt53_forward (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        op1,
        op2,
        p_low_03,
        p_low_03_ap_vld,
        p_low_47,
        p_low_47_ap_vld,
        p_high_03,
        p_high_03_ap_vld,
        p_high_47,
        p_high_47_ap_vld
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] op1;
input  [63:0] op2;
output  [63:0] p_low_03;
output   p_low_03_ap_vld;
output  [63:0] p_low_47;
output   p_low_47_ap_vld;
output  [63:0] p_high_03;
output   p_high_03_ap_vld;
output  [63:0] p_high_47;
output   p_high_47_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_low_03_ap_vld;
reg p_low_47_ap_vld;
reg p_high_03_ap_vld;
reg p_high_47_ap_vld;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire  signed [7:0] inputs_fu_124_p4;
wire  signed [7:0] inputs_17_fu_144_p4;
wire  signed [7:0] inputs_19_fu_164_p4;
wire  signed [7:0] inputs_21_fu_184_p4;
wire  signed [7:0] inputs_23_fu_198_p4;
wire  signed [7:0] inputs_25_fu_218_p4;
wire  signed [7:0] inputs_27_fu_238_p4;
wire  signed [7:0] inputs_29_fu_258_p4;
wire   [7:0] inputs_16_fu_134_p4;
wire   [7:0] inputs_18_fu_154_p4;
wire   [7:0] inputs_20_fu_174_p4;
wire   [7:0] inputs_22_fu_194_p1;
wire   [7:0] inputs_24_fu_208_p4;
wire   [7:0] inputs_26_fu_228_p4;
wire   [7:0] inputs_28_fu_248_p4;
wire   [7:0] inputs_30_fu_268_p1;
wire  signed [8:0] sext_ln44_1_fu_276_p1;
wire  signed [8:0] sext_ln44_fu_272_p1;
wire   [8:0] add_ln65_fu_336_p2;
wire   [7:0] trunc_ln_fu_342_p4;
wire  signed [8:0] sext_ln45_fu_304_p1;
wire  signed [8:0] sext_ln65_fu_352_p1;
wire  signed [8:0] d_fu_356_p2;
wire  signed [8:0] sext_ln44_2_fu_280_p1;
wire   [8:0] add_ln66_fu_366_p2;
wire   [7:0] trunc_ln1_fu_372_p4;
wire  signed [8:0] sext_ln45_1_fu_308_p1;
wire  signed [8:0] sext_ln66_fu_382_p1;
wire  signed [8:0] d_16_fu_386_p2;
wire  signed [8:0] sext_ln44_3_fu_284_p1;
wire   [8:0] add_ln67_fu_396_p2;
wire   [7:0] trunc_ln2_fu_402_p4;
wire  signed [8:0] sext_ln45_2_fu_312_p1;
wire  signed [8:0] sext_ln67_fu_412_p1;
wire  signed [8:0] d_10_fu_416_p2;
wire  signed [8:0] sext_ln44_4_fu_288_p1;
wire   [8:0] add_ln68_fu_430_p2;
wire   [7:0] trunc_ln3_fu_436_p4;
wire  signed [8:0] sext_ln45_3_fu_316_p1;
wire  signed [8:0] sext_ln68_fu_446_p1;
wire  signed [8:0] d_17_fu_450_p2;
wire  signed [8:0] sext_ln44_5_fu_292_p1;
wire   [8:0] add_ln69_fu_464_p2;
wire   [7:0] trunc_ln4_fu_470_p4;
wire  signed [8:0] sext_ln45_4_fu_320_p1;
wire  signed [8:0] sext_ln69_fu_480_p1;
wire  signed [8:0] d_18_fu_484_p2;
wire  signed [8:0] sext_ln44_6_fu_296_p1;
wire   [8:0] add_ln70_fu_498_p2;
wire   [7:0] trunc_ln5_fu_504_p4;
wire  signed [8:0] sext_ln45_5_fu_324_p1;
wire  signed [8:0] sext_ln70_fu_514_p1;
wire  signed [8:0] d_19_fu_518_p2;
wire  signed [8:0] sext_ln44_7_fu_300_p1;
wire   [8:0] add_ln71_fu_532_p2;
wire   [7:0] trunc_ln6_fu_538_p4;
wire  signed [8:0] sext_ln45_6_fu_328_p1;
wire  signed [8:0] sext_ln71_fu_548_p1;
wire  signed [8:0] d_14_fu_552_p2;
wire   [8:0] add_ln72_fu_566_p2;
wire   [7:0] trunc_ln7_fu_572_p4;
wire  signed [8:0] sext_ln45_7_fu_332_p1;
wire  signed [8:0] sext_ln72_fu_582_p1;
wire  signed [8:0] d_20_fu_586_p2;
wire  signed [9:0] sext_ln45_8_fu_362_p1;
wire   [9:0] add_ln74_fu_600_p2;
wire  signed [10:0] sext_ln45_21_fu_596_p1;
wire  signed [10:0] sext_ln74_1_fu_606_p1;
wire   [10:0] add_ln74_1_fu_610_p2;
wire   [8:0] tmp_fu_620_p4;
wire  signed [10:0] sext_ln45_9_fu_392_p1;
wire   [10:0] add_ln75_fu_634_p2;
wire   [8:0] tmp_1_fu_644_p4;
wire  signed [9:0] sext_ln45_11_fu_426_p1;
wire   [9:0] add_ln76_fu_658_p2;
wire  signed [10:0] sext_ln76_1_fu_664_p1;
wire   [10:0] add_ln76_1_fu_668_p2;
wire   [8:0] tmp_2_fu_678_p4;
wire  signed [9:0] sext_ln45_13_fu_460_p1;
wire   [9:0] add_ln77_fu_692_p2;
wire  signed [10:0] sext_ln77_1_fu_698_p1;
wire  signed [10:0] sext_ln45_10_fu_422_p1;
wire   [10:0] add_ln77_1_fu_702_p2;
wire   [8:0] tmp_3_fu_712_p4;
wire  signed [9:0] sext_ln45_15_fu_494_p1;
wire   [9:0] add_ln78_fu_726_p2;
wire  signed [10:0] sext_ln78_1_fu_732_p1;
wire  signed [10:0] sext_ln45_12_fu_456_p1;
wire   [10:0] add_ln78_1_fu_736_p2;
wire   [8:0] tmp_4_fu_746_p4;
wire  signed [9:0] sext_ln45_17_fu_528_p1;
wire   [9:0] add_ln79_fu_760_p2;
wire  signed [10:0] sext_ln79_1_fu_766_p1;
wire  signed [10:0] sext_ln45_14_fu_490_p1;
wire   [10:0] add_ln79_1_fu_770_p2;
wire   [8:0] tmp_5_fu_780_p4;
wire  signed [9:0] sext_ln45_19_fu_562_p1;
wire   [9:0] add_ln80_fu_794_p2;
wire  signed [10:0] sext_ln80_1_fu_800_p1;
wire  signed [10:0] sext_ln45_16_fu_524_p1;
wire   [10:0] add_ln80_1_fu_804_p2;
wire   [8:0] tmp_6_fu_814_p4;
wire  signed [9:0] sext_ln45_20_fu_592_p1;
wire   [9:0] add_ln81_fu_828_p2;
wire  signed [10:0] sext_ln81_1_fu_834_p1;
wire  signed [10:0] sext_ln45_18_fu_558_p1;
wire   [10:0] add_ln81_1_fu_838_p2;
wire   [8:0] tmp_7_fu_848_p4;
wire  signed [15:0] sext_ln74_2_fu_630_p1;
wire  signed [15:0] sext_ln74_fu_616_p1;
wire  signed [15:0] sext_ln75_1_fu_654_p1;
wire  signed [15:0] sext_ln75_fu_640_p1;
wire  signed [15:0] sext_ln76_2_fu_688_p1;
wire  signed [15:0] sext_ln76_fu_674_p1;
wire  signed [15:0] sext_ln77_2_fu_722_p1;
wire  signed [15:0] sext_ln77_fu_708_p1;
wire  signed [15:0] sext_ln78_2_fu_756_p1;
wire  signed [15:0] sext_ln78_fu_742_p1;
wire  signed [15:0] sext_ln79_2_fu_790_p1;
wire  signed [15:0] sext_ln79_fu_776_p1;
wire  signed [15:0] sext_ln80_2_fu_824_p1;
wire  signed [15:0] sext_ln80_fu_810_p1;
wire  signed [15:0] sext_ln81_2_fu_858_p1;
wire  signed [15:0] sext_ln81_fu_844_p1;
wire   [15:0] low_fu_862_p2;
wire   [15:0] low_1_fu_868_p2;
wire   [15:0] low_2_fu_874_p2;
wire   [15:0] low_3_fu_880_p2;
wire   [15:0] low_4_fu_886_p2;
wire   [15:0] low_5_fu_892_p2;
wire   [15:0] low_6_fu_898_p2;
wire   [15:0] low_7_fu_904_p2;
wire  signed [15:0] sext_ln93_fu_910_p1;
wire  signed [15:0] sext_ln150_fu_952_p1;
wire  signed [15:0] sext_ln95_fu_914_p1;
wire   [56:0] or_ln2_fu_956_p5;
wire  signed [15:0] sext_ln97_fu_918_p1;
wire  signed [15:0] sext_ln157_fu_973_p1;
wire  signed [15:0] sext_ln99_fu_922_p1;
wire   [56:0] or_ln3_fu_977_p5;
wire    ap_CS_fsm_state2;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_high_03_ap_vld = 1'b1;
    end else begin
        p_high_03_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_high_47_ap_vld = 1'b1;
    end else begin
        p_high_47_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_low_03_ap_vld = 1'b1;
    end else begin
        p_low_03_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_low_47_ap_vld = 1'b1;
    end else begin
        p_low_47_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln65_fu_336_p2 = ($signed(sext_ln44_1_fu_276_p1) + $signed(sext_ln44_fu_272_p1));

assign add_ln66_fu_366_p2 = ($signed(sext_ln44_2_fu_280_p1) + $signed(sext_ln44_1_fu_276_p1));

assign add_ln67_fu_396_p2 = ($signed(sext_ln44_3_fu_284_p1) + $signed(sext_ln44_2_fu_280_p1));

assign add_ln68_fu_430_p2 = ($signed(sext_ln44_4_fu_288_p1) + $signed(sext_ln44_3_fu_284_p1));

assign add_ln69_fu_464_p2 = ($signed(sext_ln44_5_fu_292_p1) + $signed(sext_ln44_4_fu_288_p1));

assign add_ln70_fu_498_p2 = ($signed(sext_ln44_6_fu_296_p1) + $signed(sext_ln44_5_fu_292_p1));

assign add_ln71_fu_532_p2 = ($signed(sext_ln44_7_fu_300_p1) + $signed(sext_ln44_6_fu_296_p1));

assign add_ln72_fu_566_p2 = ($signed(sext_ln44_7_fu_300_p1) + $signed(sext_ln44_fu_272_p1));

assign add_ln74_1_fu_610_p2 = ($signed(sext_ln45_21_fu_596_p1) + $signed(sext_ln74_1_fu_606_p1));

assign add_ln74_fu_600_p2 = ($signed(sext_ln45_8_fu_362_p1) + $signed(10'd2));

assign add_ln75_fu_634_p2 = ($signed(sext_ln74_1_fu_606_p1) + $signed(sext_ln45_9_fu_392_p1));

assign add_ln76_1_fu_668_p2 = ($signed(sext_ln76_1_fu_664_p1) + $signed(sext_ln45_9_fu_392_p1));

assign add_ln76_fu_658_p2 = ($signed(sext_ln45_11_fu_426_p1) + $signed(10'd2));

assign add_ln77_1_fu_702_p2 = ($signed(sext_ln77_1_fu_698_p1) + $signed(sext_ln45_10_fu_422_p1));

assign add_ln77_fu_692_p2 = ($signed(sext_ln45_13_fu_460_p1) + $signed(10'd2));

assign add_ln78_1_fu_736_p2 = ($signed(sext_ln78_1_fu_732_p1) + $signed(sext_ln45_12_fu_456_p1));

assign add_ln78_fu_726_p2 = ($signed(sext_ln45_15_fu_494_p1) + $signed(10'd2));

assign add_ln79_1_fu_770_p2 = ($signed(sext_ln79_1_fu_766_p1) + $signed(sext_ln45_14_fu_490_p1));

assign add_ln79_fu_760_p2 = ($signed(sext_ln45_17_fu_528_p1) + $signed(10'd2));

assign add_ln80_1_fu_804_p2 = ($signed(sext_ln80_1_fu_800_p1) + $signed(sext_ln45_16_fu_524_p1));

assign add_ln80_fu_794_p2 = ($signed(sext_ln45_19_fu_562_p1) + $signed(10'd2));

assign add_ln81_1_fu_838_p2 = ($signed(sext_ln81_1_fu_834_p1) + $signed(sext_ln45_18_fu_558_p1));

assign add_ln81_fu_828_p2 = ($signed(sext_ln45_20_fu_592_p1) + $signed(10'd2));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign d_10_fu_416_p2 = ($signed(sext_ln45_2_fu_312_p1) - $signed(sext_ln67_fu_412_p1));

assign d_14_fu_552_p2 = ($signed(sext_ln45_6_fu_328_p1) - $signed(sext_ln71_fu_548_p1));

assign d_16_fu_386_p2 = ($signed(sext_ln45_1_fu_308_p1) - $signed(sext_ln66_fu_382_p1));

assign d_17_fu_450_p2 = ($signed(sext_ln45_3_fu_316_p1) - $signed(sext_ln68_fu_446_p1));

assign d_18_fu_484_p2 = ($signed(sext_ln45_4_fu_320_p1) - $signed(sext_ln69_fu_480_p1));

assign d_19_fu_518_p2 = ($signed(sext_ln45_5_fu_324_p1) - $signed(sext_ln70_fu_514_p1));

assign d_20_fu_586_p2 = ($signed(sext_ln45_7_fu_332_p1) - $signed(sext_ln72_fu_582_p1));

assign d_fu_356_p2 = ($signed(sext_ln45_fu_304_p1) - $signed(sext_ln65_fu_352_p1));

assign inputs_16_fu_134_p4 = {{op1[55:48]}};

assign inputs_17_fu_144_p4 = {{op1[47:40]}};

assign inputs_18_fu_154_p4 = {{op1[39:32]}};

assign inputs_19_fu_164_p4 = {{op1[31:24]}};

assign inputs_20_fu_174_p4 = {{op1[23:16]}};

assign inputs_21_fu_184_p4 = {{op1[15:8]}};

assign inputs_22_fu_194_p1 = op1[7:0];

assign inputs_23_fu_198_p4 = {{op2[63:56]}};

assign inputs_24_fu_208_p4 = {{op2[55:48]}};

assign inputs_25_fu_218_p4 = {{op2[47:40]}};

assign inputs_26_fu_228_p4 = {{op2[39:32]}};

assign inputs_27_fu_238_p4 = {{op2[31:24]}};

assign inputs_28_fu_248_p4 = {{op2[23:16]}};

assign inputs_29_fu_258_p4 = {{op2[15:8]}};

assign inputs_30_fu_268_p1 = op2[7:0];

assign inputs_fu_124_p4 = {{op1[63:56]}};

assign low_1_fu_868_p2 = ($signed(sext_ln75_1_fu_654_p1) + $signed(sext_ln75_fu_640_p1));

assign low_2_fu_874_p2 = ($signed(sext_ln76_2_fu_688_p1) + $signed(sext_ln76_fu_674_p1));

assign low_3_fu_880_p2 = ($signed(sext_ln77_2_fu_722_p1) + $signed(sext_ln77_fu_708_p1));

assign low_4_fu_886_p2 = ($signed(sext_ln78_2_fu_756_p1) + $signed(sext_ln78_fu_742_p1));

assign low_5_fu_892_p2 = ($signed(sext_ln79_2_fu_790_p1) + $signed(sext_ln79_fu_776_p1));

assign low_6_fu_898_p2 = ($signed(sext_ln80_2_fu_824_p1) + $signed(sext_ln80_fu_810_p1));

assign low_7_fu_904_p2 = ($signed(sext_ln81_2_fu_858_p1) + $signed(sext_ln81_fu_844_p1));

assign low_fu_862_p2 = ($signed(sext_ln74_2_fu_630_p1) + $signed(sext_ln74_fu_616_p1));

assign or_ln2_fu_956_p5 = {{{{d_fu_356_p2}, {sext_ln93_fu_910_p1}}, {sext_ln150_fu_952_p1}}, {sext_ln95_fu_914_p1}};

assign or_ln3_fu_977_p5 = {{{{d_18_fu_484_p2}, {sext_ln97_fu_918_p1}}, {sext_ln157_fu_973_p1}}, {sext_ln99_fu_922_p1}};

assign p_high_03 = $signed(or_ln2_fu_956_p5);

assign p_high_47 = $signed(or_ln3_fu_977_p5);

assign p_low_03 = {{{{low_fu_862_p2}, {low_1_fu_868_p2}}, {low_2_fu_874_p2}}, {low_3_fu_880_p2}};

assign p_low_47 = {{{{low_4_fu_886_p2}, {low_5_fu_892_p2}}, {low_6_fu_898_p2}}, {low_7_fu_904_p2}};

assign sext_ln150_fu_952_p1 = d_10_fu_416_p2;

assign sext_ln157_fu_973_p1 = d_14_fu_552_p2;

assign sext_ln44_1_fu_276_p1 = inputs_17_fu_144_p4;

assign sext_ln44_2_fu_280_p1 = inputs_19_fu_164_p4;

assign sext_ln44_3_fu_284_p1 = inputs_21_fu_184_p4;

assign sext_ln44_4_fu_288_p1 = inputs_23_fu_198_p4;

assign sext_ln44_5_fu_292_p1 = inputs_25_fu_218_p4;

assign sext_ln44_6_fu_296_p1 = inputs_27_fu_238_p4;

assign sext_ln44_7_fu_300_p1 = inputs_29_fu_258_p4;

assign sext_ln44_fu_272_p1 = inputs_fu_124_p4;

assign sext_ln45_10_fu_422_p1 = d_10_fu_416_p2;

assign sext_ln45_11_fu_426_p1 = d_10_fu_416_p2;

assign sext_ln45_12_fu_456_p1 = d_17_fu_450_p2;

assign sext_ln45_13_fu_460_p1 = d_17_fu_450_p2;

assign sext_ln45_14_fu_490_p1 = d_18_fu_484_p2;

assign sext_ln45_15_fu_494_p1 = d_18_fu_484_p2;

assign sext_ln45_16_fu_524_p1 = d_19_fu_518_p2;

assign sext_ln45_17_fu_528_p1 = d_19_fu_518_p2;

assign sext_ln45_18_fu_558_p1 = d_14_fu_552_p2;

assign sext_ln45_19_fu_562_p1 = d_14_fu_552_p2;

assign sext_ln45_1_fu_308_p1 = $signed(inputs_18_fu_154_p4);

assign sext_ln45_20_fu_592_p1 = d_20_fu_586_p2;

assign sext_ln45_21_fu_596_p1 = d_20_fu_586_p2;

assign sext_ln45_2_fu_312_p1 = $signed(inputs_20_fu_174_p4);

assign sext_ln45_3_fu_316_p1 = $signed(inputs_22_fu_194_p1);

assign sext_ln45_4_fu_320_p1 = $signed(inputs_24_fu_208_p4);

assign sext_ln45_5_fu_324_p1 = $signed(inputs_26_fu_228_p4);

assign sext_ln45_6_fu_328_p1 = $signed(inputs_28_fu_248_p4);

assign sext_ln45_7_fu_332_p1 = $signed(inputs_30_fu_268_p1);

assign sext_ln45_8_fu_362_p1 = d_fu_356_p2;

assign sext_ln45_9_fu_392_p1 = d_16_fu_386_p2;

assign sext_ln45_fu_304_p1 = $signed(inputs_16_fu_134_p4);

assign sext_ln65_fu_352_p1 = $signed(trunc_ln_fu_342_p4);

assign sext_ln66_fu_382_p1 = $signed(trunc_ln1_fu_372_p4);

assign sext_ln67_fu_412_p1 = $signed(trunc_ln2_fu_402_p4);

assign sext_ln68_fu_446_p1 = $signed(trunc_ln3_fu_436_p4);

assign sext_ln69_fu_480_p1 = $signed(trunc_ln4_fu_470_p4);

assign sext_ln70_fu_514_p1 = $signed(trunc_ln5_fu_504_p4);

assign sext_ln71_fu_548_p1 = $signed(trunc_ln6_fu_538_p4);

assign sext_ln72_fu_582_p1 = $signed(trunc_ln7_fu_572_p4);

assign sext_ln74_1_fu_606_p1 = $signed(add_ln74_fu_600_p2);

assign sext_ln74_2_fu_630_p1 = $signed(tmp_fu_620_p4);

assign sext_ln74_fu_616_p1 = inputs_fu_124_p4;

assign sext_ln75_1_fu_654_p1 = $signed(tmp_1_fu_644_p4);

assign sext_ln75_fu_640_p1 = inputs_17_fu_144_p4;

assign sext_ln76_1_fu_664_p1 = $signed(add_ln76_fu_658_p2);

assign sext_ln76_2_fu_688_p1 = $signed(tmp_2_fu_678_p4);

assign sext_ln76_fu_674_p1 = inputs_19_fu_164_p4;

assign sext_ln77_1_fu_698_p1 = $signed(add_ln77_fu_692_p2);

assign sext_ln77_2_fu_722_p1 = $signed(tmp_3_fu_712_p4);

assign sext_ln77_fu_708_p1 = inputs_21_fu_184_p4;

assign sext_ln78_1_fu_732_p1 = $signed(add_ln78_fu_726_p2);

assign sext_ln78_2_fu_756_p1 = $signed(tmp_4_fu_746_p4);

assign sext_ln78_fu_742_p1 = inputs_23_fu_198_p4;

assign sext_ln79_1_fu_766_p1 = $signed(add_ln79_fu_760_p2);

assign sext_ln79_2_fu_790_p1 = $signed(tmp_5_fu_780_p4);

assign sext_ln79_fu_776_p1 = inputs_25_fu_218_p4;

assign sext_ln80_1_fu_800_p1 = $signed(add_ln80_fu_794_p2);

assign sext_ln80_2_fu_824_p1 = $signed(tmp_6_fu_814_p4);

assign sext_ln80_fu_810_p1 = inputs_27_fu_238_p4;

assign sext_ln81_1_fu_834_p1 = $signed(add_ln81_fu_828_p2);

assign sext_ln81_2_fu_858_p1 = $signed(tmp_7_fu_848_p4);

assign sext_ln81_fu_844_p1 = inputs_29_fu_258_p4;

assign sext_ln93_fu_910_p1 = d_16_fu_386_p2;

assign sext_ln95_fu_914_p1 = d_17_fu_450_p2;

assign sext_ln97_fu_918_p1 = d_19_fu_518_p2;

assign sext_ln99_fu_922_p1 = d_20_fu_586_p2;

assign tmp_1_fu_644_p4 = {{add_ln75_fu_634_p2[10:2]}};

assign tmp_2_fu_678_p4 = {{add_ln76_1_fu_668_p2[10:2]}};

assign tmp_3_fu_712_p4 = {{add_ln77_1_fu_702_p2[10:2]}};

assign tmp_4_fu_746_p4 = {{add_ln78_1_fu_736_p2[10:2]}};

assign tmp_5_fu_780_p4 = {{add_ln79_1_fu_770_p2[10:2]}};

assign tmp_6_fu_814_p4 = {{add_ln80_1_fu_804_p2[10:2]}};

assign tmp_7_fu_848_p4 = {{add_ln81_1_fu_838_p2[10:2]}};

assign tmp_fu_620_p4 = {{add_ln74_1_fu_610_p2[10:2]}};

assign trunc_ln1_fu_372_p4 = {{add_ln66_fu_366_p2[8:1]}};

assign trunc_ln2_fu_402_p4 = {{add_ln67_fu_396_p2[8:1]}};

assign trunc_ln3_fu_436_p4 = {{add_ln68_fu_430_p2[8:1]}};

assign trunc_ln4_fu_470_p4 = {{add_ln69_fu_464_p2[8:1]}};

assign trunc_ln5_fu_504_p4 = {{add_ln70_fu_498_p2[8:1]}};

assign trunc_ln6_fu_538_p4 = {{add_ln71_fu_532_p2[8:1]}};

assign trunc_ln7_fu_572_p4 = {{add_ln72_fu_566_p2[8:1]}};

assign trunc_ln_fu_342_p4 = {{add_ln65_fu_336_p2[8:1]}};

endmodule //HW_dwt53_forward
