-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity HW_dwt53_inverse is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    low_03 : IN STD_LOGIC_VECTOR (63 downto 0);
    low_47 : IN STD_LOGIC_VECTOR (63 downto 0);
    high_03 : IN STD_LOGIC_VECTOR (63 downto 0);
    high_47 : IN STD_LOGIC_VECTOR (63 downto 0);
    p_out_0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    p_out_0_ap_vld : OUT STD_LOGIC;
    p_out_1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    p_out_1_ap_vld : OUT STD_LOGIC );
end;


architecture behav of HW_dwt53_inverse is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "HW_dwt53_inverse_HW_dwt53_inverse,hls_ip_2024_2,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcku5p-ffvb676-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.627250,HLS_SYN_LAT=1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=2,HLS_SYN_LUT=2286,HLS_VERSION=2024_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal call_ret_HW_dwt53_inverse_core_fu_94_ap_ready : STD_LOGIC;
    signal call_ret_HW_dwt53_inverse_core_fu_94_low_read : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_HW_dwt53_inverse_core_fu_94_low_read_23 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_HW_dwt53_inverse_core_fu_94_low_read_24 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_HW_dwt53_inverse_core_fu_94_low_read_25 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_HW_dwt53_inverse_core_fu_94_low_read_26 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_HW_dwt53_inverse_core_fu_94_low_read_27 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_HW_dwt53_inverse_core_fu_94_low_read_28 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_HW_dwt53_inverse_core_fu_94_low_read_29 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_HW_dwt53_inverse_core_fu_94_high_read : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_HW_dwt53_inverse_core_fu_94_high_read_23 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_HW_dwt53_inverse_core_fu_94_high_read_24 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_HW_dwt53_inverse_core_fu_94_high_read_25 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_HW_dwt53_inverse_core_fu_94_high_read_26 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_HW_dwt53_inverse_core_fu_94_high_read_27 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_HW_dwt53_inverse_core_fu_94_high_read_28 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_HW_dwt53_inverse_core_fu_94_high_read_29 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_HW_dwt53_inverse_core_fu_94_ap_return_0 : STD_LOGIC_VECTOR (7 downto 0);
    signal call_ret_HW_dwt53_inverse_core_fu_94_ap_return_1 : STD_LOGIC_VECTOR (7 downto 0);
    signal call_ret_HW_dwt53_inverse_core_fu_94_ap_return_2 : STD_LOGIC_VECTOR (7 downto 0);
    signal call_ret_HW_dwt53_inverse_core_fu_94_ap_return_3 : STD_LOGIC_VECTOR (7 downto 0);
    signal call_ret_HW_dwt53_inverse_core_fu_94_ap_return_4 : STD_LOGIC_VECTOR (7 downto 0);
    signal call_ret_HW_dwt53_inverse_core_fu_94_ap_return_5 : STD_LOGIC_VECTOR (7 downto 0);
    signal call_ret_HW_dwt53_inverse_core_fu_94_ap_return_6 : STD_LOGIC_VECTOR (7 downto 0);
    signal call_ret_HW_dwt53_inverse_core_fu_94_ap_return_7 : STD_LOGIC_VECTOR (7 downto 0);
    signal call_ret_HW_dwt53_inverse_core_fu_94_ap_return_8 : STD_LOGIC_VECTOR (7 downto 0);
    signal call_ret_HW_dwt53_inverse_core_fu_94_ap_return_9 : STD_LOGIC_VECTOR (7 downto 0);
    signal call_ret_HW_dwt53_inverse_core_fu_94_ap_return_10 : STD_LOGIC_VECTOR (7 downto 0);
    signal call_ret_HW_dwt53_inverse_core_fu_94_ap_return_11 : STD_LOGIC_VECTOR (7 downto 0);
    signal call_ret_HW_dwt53_inverse_core_fu_94_ap_return_12 : STD_LOGIC_VECTOR (7 downto 0);
    signal call_ret_HW_dwt53_inverse_core_fu_94_ap_return_13 : STD_LOGIC_VECTOR (7 downto 0);
    signal call_ret_HW_dwt53_inverse_core_fu_94_ap_return_14 : STD_LOGIC_VECTOR (7 downto 0);
    signal call_ret_HW_dwt53_inverse_core_fu_94_ap_return_15 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component HW_dwt53_inverse_HW_dwt53_inverse_core IS
    port (
        ap_ready : OUT STD_LOGIC;
        low_read : IN STD_LOGIC_VECTOR (15 downto 0);
        low_read_23 : IN STD_LOGIC_VECTOR (15 downto 0);
        low_read_24 : IN STD_LOGIC_VECTOR (15 downto 0);
        low_read_25 : IN STD_LOGIC_VECTOR (15 downto 0);
        low_read_26 : IN STD_LOGIC_VECTOR (15 downto 0);
        low_read_27 : IN STD_LOGIC_VECTOR (15 downto 0);
        low_read_28 : IN STD_LOGIC_VECTOR (15 downto 0);
        low_read_29 : IN STD_LOGIC_VECTOR (15 downto 0);
        high_read : IN STD_LOGIC_VECTOR (15 downto 0);
        high_read_23 : IN STD_LOGIC_VECTOR (15 downto 0);
        high_read_24 : IN STD_LOGIC_VECTOR (15 downto 0);
        high_read_25 : IN STD_LOGIC_VECTOR (15 downto 0);
        high_read_26 : IN STD_LOGIC_VECTOR (15 downto 0);
        high_read_27 : IN STD_LOGIC_VECTOR (15 downto 0);
        high_read_28 : IN STD_LOGIC_VECTOR (15 downto 0);
        high_read_29 : IN STD_LOGIC_VECTOR (15 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (7 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (7 downto 0);
        ap_return_4 : OUT STD_LOGIC_VECTOR (7 downto 0);
        ap_return_5 : OUT STD_LOGIC_VECTOR (7 downto 0);
        ap_return_6 : OUT STD_LOGIC_VECTOR (7 downto 0);
        ap_return_7 : OUT STD_LOGIC_VECTOR (7 downto 0);
        ap_return_8 : OUT STD_LOGIC_VECTOR (7 downto 0);
        ap_return_9 : OUT STD_LOGIC_VECTOR (7 downto 0);
        ap_return_10 : OUT STD_LOGIC_VECTOR (7 downto 0);
        ap_return_11 : OUT STD_LOGIC_VECTOR (7 downto 0);
        ap_return_12 : OUT STD_LOGIC_VECTOR (7 downto 0);
        ap_return_13 : OUT STD_LOGIC_VECTOR (7 downto 0);
        ap_return_14 : OUT STD_LOGIC_VECTOR (7 downto 0);
        ap_return_15 : OUT STD_LOGIC_VECTOR (7 downto 0);
        ap_rst : IN STD_LOGIC );
    end component;



begin
    call_ret_HW_dwt53_inverse_core_fu_94 : component HW_dwt53_inverse_HW_dwt53_inverse_core
    port map (
        ap_ready => call_ret_HW_dwt53_inverse_core_fu_94_ap_ready,
        low_read => call_ret_HW_dwt53_inverse_core_fu_94_low_read,
        low_read_23 => call_ret_HW_dwt53_inverse_core_fu_94_low_read_23,
        low_read_24 => call_ret_HW_dwt53_inverse_core_fu_94_low_read_24,
        low_read_25 => call_ret_HW_dwt53_inverse_core_fu_94_low_read_25,
        low_read_26 => call_ret_HW_dwt53_inverse_core_fu_94_low_read_26,
        low_read_27 => call_ret_HW_dwt53_inverse_core_fu_94_low_read_27,
        low_read_28 => call_ret_HW_dwt53_inverse_core_fu_94_low_read_28,
        low_read_29 => call_ret_HW_dwt53_inverse_core_fu_94_low_read_29,
        high_read => call_ret_HW_dwt53_inverse_core_fu_94_high_read,
        high_read_23 => call_ret_HW_dwt53_inverse_core_fu_94_high_read_23,
        high_read_24 => call_ret_HW_dwt53_inverse_core_fu_94_high_read_24,
        high_read_25 => call_ret_HW_dwt53_inverse_core_fu_94_high_read_25,
        high_read_26 => call_ret_HW_dwt53_inverse_core_fu_94_high_read_26,
        high_read_27 => call_ret_HW_dwt53_inverse_core_fu_94_high_read_27,
        high_read_28 => call_ret_HW_dwt53_inverse_core_fu_94_high_read_28,
        high_read_29 => call_ret_HW_dwt53_inverse_core_fu_94_high_read_29,
        ap_return_0 => call_ret_HW_dwt53_inverse_core_fu_94_ap_return_0,
        ap_return_1 => call_ret_HW_dwt53_inverse_core_fu_94_ap_return_1,
        ap_return_2 => call_ret_HW_dwt53_inverse_core_fu_94_ap_return_2,
        ap_return_3 => call_ret_HW_dwt53_inverse_core_fu_94_ap_return_3,
        ap_return_4 => call_ret_HW_dwt53_inverse_core_fu_94_ap_return_4,
        ap_return_5 => call_ret_HW_dwt53_inverse_core_fu_94_ap_return_5,
        ap_return_6 => call_ret_HW_dwt53_inverse_core_fu_94_ap_return_6,
        ap_return_7 => call_ret_HW_dwt53_inverse_core_fu_94_ap_return_7,
        ap_return_8 => call_ret_HW_dwt53_inverse_core_fu_94_ap_return_8,
        ap_return_9 => call_ret_HW_dwt53_inverse_core_fu_94_ap_return_9,
        ap_return_10 => call_ret_HW_dwt53_inverse_core_fu_94_ap_return_10,
        ap_return_11 => call_ret_HW_dwt53_inverse_core_fu_94_ap_return_11,
        ap_return_12 => call_ret_HW_dwt53_inverse_core_fu_94_ap_return_12,
        ap_return_13 => call_ret_HW_dwt53_inverse_core_fu_94_ap_return_13,
        ap_return_14 => call_ret_HW_dwt53_inverse_core_fu_94_ap_return_14,
        ap_return_15 => call_ret_HW_dwt53_inverse_core_fu_94_ap_return_15,
        ap_rst => ap_rst);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    call_ret_HW_dwt53_inverse_core_fu_94_high_read <= high_03(63 downto 48);
    call_ret_HW_dwt53_inverse_core_fu_94_high_read_23 <= high_03(47 downto 32);
    call_ret_HW_dwt53_inverse_core_fu_94_high_read_24 <= high_03(31 downto 16);
    call_ret_HW_dwt53_inverse_core_fu_94_high_read_25 <= high_03(16 - 1 downto 0);
    call_ret_HW_dwt53_inverse_core_fu_94_high_read_26 <= high_47(63 downto 48);
    call_ret_HW_dwt53_inverse_core_fu_94_high_read_27 <= high_47(47 downto 32);
    call_ret_HW_dwt53_inverse_core_fu_94_high_read_28 <= high_47(31 downto 16);
    call_ret_HW_dwt53_inverse_core_fu_94_high_read_29 <= high_47(16 - 1 downto 0);
    call_ret_HW_dwt53_inverse_core_fu_94_low_read <= low_03(63 downto 48);
    call_ret_HW_dwt53_inverse_core_fu_94_low_read_23 <= low_03(47 downto 32);
    call_ret_HW_dwt53_inverse_core_fu_94_low_read_24 <= low_03(31 downto 16);
    call_ret_HW_dwt53_inverse_core_fu_94_low_read_25 <= low_03(16 - 1 downto 0);
    call_ret_HW_dwt53_inverse_core_fu_94_low_read_26 <= low_47(63 downto 48);
    call_ret_HW_dwt53_inverse_core_fu_94_low_read_27 <= low_47(47 downto 32);
    call_ret_HW_dwt53_inverse_core_fu_94_low_read_28 <= low_47(31 downto 16);
    call_ret_HW_dwt53_inverse_core_fu_94_low_read_29 <= low_47(16 - 1 downto 0);
    p_out_0 <= (((((((call_ret_HW_dwt53_inverse_core_fu_94_ap_return_0 & call_ret_HW_dwt53_inverse_core_fu_94_ap_return_1) & call_ret_HW_dwt53_inverse_core_fu_94_ap_return_2) & call_ret_HW_dwt53_inverse_core_fu_94_ap_return_3) & call_ret_HW_dwt53_inverse_core_fu_94_ap_return_4) & call_ret_HW_dwt53_inverse_core_fu_94_ap_return_5) & call_ret_HW_dwt53_inverse_core_fu_94_ap_return_6) & call_ret_HW_dwt53_inverse_core_fu_94_ap_return_7);

    p_out_0_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_out_0_ap_vld <= ap_const_logic_1;
        else 
            p_out_0_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_out_1 <= (((((((call_ret_HW_dwt53_inverse_core_fu_94_ap_return_8 & call_ret_HW_dwt53_inverse_core_fu_94_ap_return_9) & call_ret_HW_dwt53_inverse_core_fu_94_ap_return_10) & call_ret_HW_dwt53_inverse_core_fu_94_ap_return_11) & call_ret_HW_dwt53_inverse_core_fu_94_ap_return_12) & call_ret_HW_dwt53_inverse_core_fu_94_ap_return_13) & call_ret_HW_dwt53_inverse_core_fu_94_ap_return_14) & call_ret_HW_dwt53_inverse_core_fu_94_ap_return_15);

    p_out_1_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_out_1_ap_vld <= ap_const_logic_1;
        else 
            p_out_1_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

end behav;
