// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module HW_dwt53_inverse_HW_dwt53_inverse_core (
        ap_ready,
        low_read,
        low_read_23,
        low_read_24,
        low_read_25,
        low_read_26,
        low_read_27,
        low_read_28,
        low_read_29,
        high_read,
        high_read_23,
        high_read_24,
        high_read_25,
        high_read_26,
        high_read_27,
        high_read_28,
        high_read_29,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_rst
);


output   ap_ready;
input  [15:0] low_read;
input  [15:0] low_read_23;
input  [15:0] low_read_24;
input  [15:0] low_read_25;
input  [15:0] low_read_26;
input  [15:0] low_read_27;
input  [15:0] low_read_28;
input  [15:0] low_read_29;
input  [15:0] high_read;
input  [15:0] high_read_23;
input  [15:0] high_read_24;
input  [15:0] high_read_25;
input  [15:0] high_read_26;
input  [15:0] high_read_27;
input  [15:0] high_read_28;
input  [15:0] high_read_29;
output  [7:0] ap_return_0;
output  [7:0] ap_return_1;
output  [7:0] ap_return_2;
output  [7:0] ap_return_3;
output  [7:0] ap_return_4;
output  [7:0] ap_return_5;
output  [7:0] ap_return_6;
output  [7:0] ap_return_7;
output  [7:0] ap_return_8;
output  [7:0] ap_return_9;
output  [7:0] ap_return_10;
output  [7:0] ap_return_11;
output  [7:0] ap_return_12;
output  [7:0] ap_return_13;
output  [7:0] ap_return_14;
output  [7:0] ap_return_15;
input   ap_rst;

wire  signed [15:0] sext_ln209_fu_198_p0;
wire  signed [15:0] sext_ln198_fu_202_p0;
wire  signed [15:0] sext_ln210_fu_206_p0;
wire  signed [15:0] sext_ln198_1_fu_210_p0;
wire  signed [15:0] sext_ln211_fu_214_p0;
wire  signed [15:0] sext_ln198_2_fu_218_p0;
wire  signed [15:0] sext_ln198_3_fu_222_p0;
wire  signed [15:0] sext_ln212_fu_226_p0;
wire  signed [15:0] sext_ln198_4_fu_230_p0;
wire  signed [15:0] sext_ln198_5_fu_234_p0;
wire  signed [15:0] sext_ln213_fu_238_p0;
wire  signed [15:0] sext_ln198_6_fu_242_p0;
wire  signed [15:0] sext_ln198_7_fu_246_p0;
wire  signed [15:0] sext_ln214_fu_250_p0;
wire  signed [15:0] sext_ln198_8_fu_254_p0;
wire  signed [15:0] sext_ln198_9_fu_258_p0;
wire  signed [15:0] sext_ln215_fu_262_p0;
wire  signed [15:0] sext_ln198_10_fu_266_p0;
wire  signed [15:0] sext_ln198_11_fu_270_p0;
wire  signed [15:0] sext_ln216_fu_274_p0;
wire  signed [15:0] sext_ln198_12_fu_278_p0;
wire  signed [15:0] sext_ln198_13_fu_282_p0;
wire  signed [16:0] sext_ln198_fu_202_p1;
wire   [16:0] add_ln218_fu_286_p2;
wire  signed [17:0] sext_ln218_fu_292_p1;
wire  signed [17:0] sext_ln198_13_fu_282_p1;
wire   [17:0] add_ln218_1_fu_296_p2;
wire   [15:0] trunc_ln_fu_302_p4;
wire  signed [16:0] sext_ln197_fu_166_p1;
wire  signed [16:0] sext_ln218_1_fu_312_p1;
wire  signed [16:0] s_fu_316_p2;
wire  signed [17:0] sext_ln198_1_fu_210_p1;
wire   [17:0] add_ln219_fu_326_p2;
wire   [15:0] trunc_ln1_fu_332_p4;
wire  signed [16:0] sext_ln197_1_fu_170_p1;
wire  signed [16:0] sext_ln219_fu_342_p1;
wire  signed [16:0] s_1_fu_346_p2;
wire  signed [16:0] sext_ln198_3_fu_222_p1;
wire   [16:0] add_ln220_fu_356_p2;
wire  signed [17:0] sext_ln220_fu_362_p1;
wire   [17:0] add_ln220_1_fu_366_p2;
wire   [15:0] trunc_ln2_fu_372_p4;
wire  signed [16:0] sext_ln197_2_fu_174_p1;
wire  signed [16:0] sext_ln220_1_fu_382_p1;
wire  signed [16:0] s_2_fu_386_p2;
wire  signed [16:0] sext_ln198_5_fu_234_p1;
wire   [16:0] add_ln221_fu_396_p2;
wire  signed [17:0] sext_ln221_fu_402_p1;
wire  signed [17:0] sext_ln198_2_fu_218_p1;
wire   [17:0] add_ln221_1_fu_406_p2;
wire   [15:0] trunc_ln3_fu_412_p4;
wire  signed [16:0] sext_ln197_3_fu_178_p1;
wire  signed [16:0] sext_ln221_1_fu_422_p1;
wire  signed [16:0] s_3_fu_426_p2;
wire  signed [16:0] sext_ln198_7_fu_246_p1;
wire   [16:0] add_ln222_fu_436_p2;
wire  signed [17:0] sext_ln222_fu_442_p1;
wire  signed [17:0] sext_ln198_4_fu_230_p1;
wire   [17:0] add_ln222_1_fu_446_p2;
wire   [15:0] trunc_ln4_fu_452_p4;
wire  signed [16:0] sext_ln197_4_fu_182_p1;
wire  signed [16:0] sext_ln222_1_fu_462_p1;
wire  signed [16:0] s_4_fu_466_p2;
wire  signed [16:0] sext_ln198_9_fu_258_p1;
wire   [16:0] add_ln223_fu_476_p2;
wire  signed [17:0] sext_ln223_fu_482_p1;
wire  signed [17:0] sext_ln198_6_fu_242_p1;
wire   [17:0] add_ln223_1_fu_486_p2;
wire   [15:0] trunc_ln5_fu_492_p4;
wire  signed [16:0] sext_ln197_5_fu_186_p1;
wire  signed [16:0] sext_ln223_1_fu_502_p1;
wire  signed [16:0] s_5_fu_506_p2;
wire  signed [16:0] sext_ln198_11_fu_270_p1;
wire   [16:0] add_ln224_fu_516_p2;
wire  signed [17:0] sext_ln224_fu_522_p1;
wire  signed [17:0] sext_ln198_8_fu_254_p1;
wire   [17:0] add_ln224_1_fu_526_p2;
wire   [15:0] trunc_ln6_fu_532_p4;
wire  signed [16:0] sext_ln197_6_fu_190_p1;
wire  signed [16:0] sext_ln224_1_fu_542_p1;
wire  signed [16:0] s_6_fu_546_p2;
wire  signed [16:0] sext_ln198_12_fu_278_p1;
wire   [16:0] add_ln225_fu_556_p2;
wire  signed [17:0] sext_ln225_fu_562_p1;
wire  signed [17:0] sext_ln198_10_fu_266_p1;
wire   [17:0] add_ln225_1_fu_566_p2;
wire   [15:0] trunc_ln7_fu_572_p4;
wire  signed [16:0] sext_ln197_7_fu_194_p1;
wire  signed [16:0] sext_ln225_1_fu_582_p1;
wire  signed [16:0] s_7_fu_586_p2;
wire   [9:0] tmp_fu_596_p4;
wire   [0:0] icmp_ln10_fu_606_p2;
wire   [0:0] icmp_ln11_fu_612_p2;
wire   [0:0] or_ln10_fu_630_p2;
wire   [7:0] select_ln10_fu_622_p3;
wire   [7:0] trunc_ln12_fu_618_p1;
wire   [9:0] tmp_1_fu_644_p4;
wire   [0:0] icmp_ln10_1_fu_654_p2;
wire   [0:0] icmp_ln11_1_fu_660_p2;
wire   [0:0] or_ln10_1_fu_678_p2;
wire   [7:0] select_ln10_2_fu_670_p3;
wire   [7:0] trunc_ln12_1_fu_666_p1;
wire   [9:0] tmp_2_fu_692_p4;
wire   [0:0] icmp_ln10_2_fu_702_p2;
wire   [0:0] icmp_ln11_2_fu_708_p2;
wire   [0:0] or_ln10_2_fu_726_p2;
wire   [7:0] select_ln10_4_fu_718_p3;
wire   [7:0] trunc_ln12_2_fu_714_p1;
wire   [9:0] tmp_3_fu_740_p4;
wire   [0:0] icmp_ln10_3_fu_750_p2;
wire   [0:0] icmp_ln11_3_fu_756_p2;
wire   [0:0] or_ln10_3_fu_774_p2;
wire   [7:0] select_ln10_6_fu_766_p3;
wire   [7:0] trunc_ln12_3_fu_762_p1;
wire   [9:0] tmp_4_fu_788_p4;
wire   [0:0] icmp_ln10_4_fu_798_p2;
wire   [0:0] icmp_ln11_4_fu_804_p2;
wire   [0:0] or_ln10_4_fu_822_p2;
wire   [7:0] select_ln10_8_fu_814_p3;
wire   [7:0] trunc_ln12_4_fu_810_p1;
wire   [9:0] tmp_5_fu_836_p4;
wire   [0:0] icmp_ln10_5_fu_846_p2;
wire   [0:0] icmp_ln11_5_fu_852_p2;
wire   [0:0] or_ln10_5_fu_870_p2;
wire   [7:0] select_ln10_10_fu_862_p3;
wire   [7:0] trunc_ln12_5_fu_858_p1;
wire   [9:0] tmp_6_fu_884_p4;
wire   [0:0] icmp_ln10_6_fu_894_p2;
wire   [0:0] icmp_ln11_6_fu_900_p2;
wire   [0:0] or_ln10_6_fu_918_p2;
wire   [7:0] select_ln10_12_fu_910_p3;
wire   [7:0] trunc_ln12_6_fu_906_p1;
wire   [9:0] tmp_7_fu_932_p4;
wire   [0:0] icmp_ln10_7_fu_942_p2;
wire   [0:0] icmp_ln11_7_fu_948_p2;
wire   [0:0] or_ln10_7_fu_966_p2;
wire   [7:0] select_ln10_14_fu_958_p3;
wire   [7:0] trunc_ln12_7_fu_954_p1;
wire  signed [17:0] sext_ln197_8_fu_322_p1;
wire  signed [17:0] sext_ln197_9_fu_352_p1;
wire   [17:0] add_ln236_fu_980_p2;
wire   [16:0] tmp_8_fu_986_p4;
wire  signed [31:0] sext_ln236_fu_996_p1;
wire  signed [31:0] sext_ln209_fu_198_p1;
wire   [31:0] add_ln236_1_fu_1000_p2;
wire   [24:0] tmp_9_fu_1006_p4;
wire   [0:0] icmp_ln10_8_fu_1016_p2;
wire   [0:0] icmp_ln11_8_fu_1022_p2;
wire   [0:0] or_ln10_8_fu_1040_p2;
wire   [7:0] select_ln10_16_fu_1032_p3;
wire   [7:0] trunc_ln12_8_fu_1028_p1;
wire  signed [17:0] sext_ln197_10_fu_392_p1;
wire   [17:0] add_ln237_fu_1054_p2;
wire   [16:0] tmp_10_fu_1060_p4;
wire  signed [31:0] sext_ln237_fu_1070_p1;
wire  signed [31:0] sext_ln210_fu_206_p1;
wire   [31:0] add_ln237_1_fu_1074_p2;
wire   [24:0] tmp_11_fu_1080_p4;
wire   [0:0] icmp_ln10_9_fu_1090_p2;
wire   [0:0] icmp_ln11_9_fu_1096_p2;
wire   [0:0] or_ln10_9_fu_1114_p2;
wire   [7:0] select_ln10_18_fu_1106_p3;
wire   [7:0] trunc_ln12_9_fu_1102_p1;
wire  signed [17:0] sext_ln197_11_fu_432_p1;
wire   [17:0] add_ln238_fu_1128_p2;
wire   [16:0] tmp_12_fu_1134_p4;
wire  signed [31:0] sext_ln238_fu_1144_p1;
wire  signed [31:0] sext_ln211_fu_214_p1;
wire   [31:0] add_ln238_1_fu_1148_p2;
wire   [24:0] tmp_13_fu_1154_p4;
wire   [0:0] icmp_ln10_10_fu_1164_p2;
wire   [0:0] icmp_ln11_10_fu_1170_p2;
wire   [0:0] or_ln10_10_fu_1188_p2;
wire   [7:0] select_ln10_20_fu_1180_p3;
wire   [7:0] trunc_ln12_10_fu_1176_p1;
wire  signed [17:0] sext_ln197_12_fu_472_p1;
wire   [17:0] add_ln239_fu_1202_p2;
wire   [16:0] tmp_14_fu_1208_p4;
wire  signed [31:0] sext_ln239_fu_1218_p1;
wire  signed [31:0] sext_ln212_fu_226_p1;
wire   [31:0] add_ln239_1_fu_1222_p2;
wire   [24:0] tmp_15_fu_1228_p4;
wire   [0:0] icmp_ln10_11_fu_1238_p2;
wire   [0:0] icmp_ln11_11_fu_1244_p2;
wire   [0:0] or_ln10_11_fu_1262_p2;
wire   [7:0] select_ln10_22_fu_1254_p3;
wire   [7:0] trunc_ln12_11_fu_1250_p1;
wire  signed [17:0] sext_ln197_13_fu_512_p1;
wire   [17:0] add_ln240_fu_1276_p2;
wire   [16:0] tmp_16_fu_1282_p4;
wire  signed [31:0] sext_ln240_fu_1292_p1;
wire  signed [31:0] sext_ln213_fu_238_p1;
wire   [31:0] add_ln240_1_fu_1296_p2;
wire   [24:0] tmp_17_fu_1302_p4;
wire   [0:0] icmp_ln10_12_fu_1312_p2;
wire   [0:0] icmp_ln11_12_fu_1318_p2;
wire   [0:0] or_ln10_12_fu_1336_p2;
wire   [7:0] select_ln10_24_fu_1328_p3;
wire   [7:0] trunc_ln12_12_fu_1324_p1;
wire  signed [17:0] sext_ln197_14_fu_552_p1;
wire   [17:0] add_ln241_fu_1350_p2;
wire   [16:0] tmp_18_fu_1356_p4;
wire  signed [31:0] sext_ln241_fu_1366_p1;
wire  signed [31:0] sext_ln214_fu_250_p1;
wire   [31:0] add_ln241_1_fu_1370_p2;
wire   [24:0] tmp_19_fu_1376_p4;
wire   [0:0] icmp_ln10_13_fu_1386_p2;
wire   [0:0] icmp_ln11_13_fu_1392_p2;
wire   [0:0] or_ln10_13_fu_1410_p2;
wire   [7:0] select_ln10_26_fu_1402_p3;
wire   [7:0] trunc_ln12_13_fu_1398_p1;
wire  signed [17:0] sext_ln197_15_fu_592_p1;
wire   [17:0] add_ln242_fu_1424_p2;
wire   [16:0] tmp_20_fu_1430_p4;
wire  signed [31:0] sext_ln242_fu_1440_p1;
wire  signed [31:0] sext_ln215_fu_262_p1;
wire   [31:0] add_ln242_1_fu_1444_p2;
wire   [24:0] tmp_21_fu_1450_p4;
wire   [0:0] icmp_ln10_14_fu_1460_p2;
wire   [0:0] icmp_ln11_14_fu_1466_p2;
wire   [0:0] or_ln10_14_fu_1484_p2;
wire   [7:0] select_ln10_28_fu_1476_p3;
wire   [7:0] trunc_ln12_14_fu_1472_p1;
wire   [17:0] add_ln243_fu_1498_p2;
wire   [16:0] tmp_22_fu_1504_p4;
wire  signed [31:0] sext_ln243_fu_1514_p1;
wire  signed [31:0] sext_ln216_fu_274_p1;
wire   [31:0] add_ln243_1_fu_1518_p2;
wire   [24:0] tmp_23_fu_1524_p4;
wire   [0:0] icmp_ln10_15_fu_1534_p2;
wire   [0:0] icmp_ln11_15_fu_1540_p2;
wire   [0:0] or_ln10_15_fu_1558_p2;
wire   [7:0] select_ln10_30_fu_1550_p3;
wire   [7:0] trunc_ln12_15_fu_1546_p1;
wire   [7:0] select_ln10_1_fu_636_p3;
wire   [7:0] select_ln10_17_fu_1046_p3;
wire   [7:0] select_ln10_3_fu_684_p3;
wire   [7:0] select_ln10_19_fu_1120_p3;
wire   [7:0] select_ln10_5_fu_732_p3;
wire   [7:0] select_ln10_21_fu_1194_p3;
wire   [7:0] select_ln10_7_fu_780_p3;
wire   [7:0] select_ln10_23_fu_1268_p3;
wire   [7:0] select_ln10_9_fu_828_p3;
wire   [7:0] select_ln10_25_fu_1342_p3;
wire   [7:0] select_ln10_11_fu_876_p3;
wire   [7:0] select_ln10_27_fu_1416_p3;
wire   [7:0] select_ln10_13_fu_924_p3;
wire   [7:0] select_ln10_29_fu_1490_p3;
wire   [7:0] select_ln10_15_fu_972_p3;
wire   [7:0] select_ln10_31_fu_1564_p3;

assign add_ln218_1_fu_296_p2 = ($signed(sext_ln218_fu_292_p1) + $signed(sext_ln198_13_fu_282_p1));

assign add_ln218_fu_286_p2 = ($signed(sext_ln198_fu_202_p1) + $signed(17'd2));

assign add_ln219_fu_326_p2 = ($signed(sext_ln218_fu_292_p1) + $signed(sext_ln198_1_fu_210_p1));

assign add_ln220_1_fu_366_p2 = ($signed(sext_ln220_fu_362_p1) + $signed(sext_ln198_1_fu_210_p1));

assign add_ln220_fu_356_p2 = ($signed(sext_ln198_3_fu_222_p1) + $signed(17'd2));

assign add_ln221_1_fu_406_p2 = ($signed(sext_ln221_fu_402_p1) + $signed(sext_ln198_2_fu_218_p1));

assign add_ln221_fu_396_p2 = ($signed(sext_ln198_5_fu_234_p1) + $signed(17'd2));

assign add_ln222_1_fu_446_p2 = ($signed(sext_ln222_fu_442_p1) + $signed(sext_ln198_4_fu_230_p1));

assign add_ln222_fu_436_p2 = ($signed(sext_ln198_7_fu_246_p1) + $signed(17'd2));

assign add_ln223_1_fu_486_p2 = ($signed(sext_ln223_fu_482_p1) + $signed(sext_ln198_6_fu_242_p1));

assign add_ln223_fu_476_p2 = ($signed(sext_ln198_9_fu_258_p1) + $signed(17'd2));

assign add_ln224_1_fu_526_p2 = ($signed(sext_ln224_fu_522_p1) + $signed(sext_ln198_8_fu_254_p1));

assign add_ln224_fu_516_p2 = ($signed(sext_ln198_11_fu_270_p1) + $signed(17'd2));

assign add_ln225_1_fu_566_p2 = ($signed(sext_ln225_fu_562_p1) + $signed(sext_ln198_10_fu_266_p1));

assign add_ln225_fu_556_p2 = ($signed(sext_ln198_12_fu_278_p1) + $signed(17'd2));

assign add_ln236_1_fu_1000_p2 = ($signed(sext_ln236_fu_996_p1) + $signed(sext_ln209_fu_198_p1));

assign add_ln236_fu_980_p2 = ($signed(sext_ln197_8_fu_322_p1) + $signed(sext_ln197_9_fu_352_p1));

assign add_ln237_1_fu_1074_p2 = ($signed(sext_ln237_fu_1070_p1) + $signed(sext_ln210_fu_206_p1));

assign add_ln237_fu_1054_p2 = ($signed(sext_ln197_10_fu_392_p1) + $signed(sext_ln197_9_fu_352_p1));

assign add_ln238_1_fu_1148_p2 = ($signed(sext_ln238_fu_1144_p1) + $signed(sext_ln211_fu_214_p1));

assign add_ln238_fu_1128_p2 = ($signed(sext_ln197_11_fu_432_p1) + $signed(sext_ln197_10_fu_392_p1));

assign add_ln239_1_fu_1222_p2 = ($signed(sext_ln239_fu_1218_p1) + $signed(sext_ln212_fu_226_p1));

assign add_ln239_fu_1202_p2 = ($signed(sext_ln197_12_fu_472_p1) + $signed(sext_ln197_11_fu_432_p1));

assign add_ln240_1_fu_1296_p2 = ($signed(sext_ln240_fu_1292_p1) + $signed(sext_ln213_fu_238_p1));

assign add_ln240_fu_1276_p2 = ($signed(sext_ln197_13_fu_512_p1) + $signed(sext_ln197_12_fu_472_p1));

assign add_ln241_1_fu_1370_p2 = ($signed(sext_ln241_fu_1366_p1) + $signed(sext_ln214_fu_250_p1));

assign add_ln241_fu_1350_p2 = ($signed(sext_ln197_14_fu_552_p1) + $signed(sext_ln197_13_fu_512_p1));

assign add_ln242_1_fu_1444_p2 = ($signed(sext_ln242_fu_1440_p1) + $signed(sext_ln215_fu_262_p1));

assign add_ln242_fu_1424_p2 = ($signed(sext_ln197_15_fu_592_p1) + $signed(sext_ln197_14_fu_552_p1));

assign add_ln243_1_fu_1518_p2 = ($signed(sext_ln243_fu_1514_p1) + $signed(sext_ln216_fu_274_p1));

assign add_ln243_fu_1498_p2 = ($signed(sext_ln197_15_fu_592_p1) + $signed(sext_ln197_8_fu_322_p1));

assign ap_ready = 1'b1;

assign or_ln10_10_fu_1188_p2 = (icmp_ln11_10_fu_1170_p2 | icmp_ln10_10_fu_1164_p2);

assign or_ln10_11_fu_1262_p2 = (icmp_ln11_11_fu_1244_p2 | icmp_ln10_11_fu_1238_p2);

assign or_ln10_12_fu_1336_p2 = (icmp_ln11_12_fu_1318_p2 | icmp_ln10_12_fu_1312_p2);

assign or_ln10_13_fu_1410_p2 = (icmp_ln11_13_fu_1392_p2 | icmp_ln10_13_fu_1386_p2);

assign or_ln10_14_fu_1484_p2 = (icmp_ln11_14_fu_1466_p2 | icmp_ln10_14_fu_1460_p2);

assign or_ln10_15_fu_1558_p2 = (icmp_ln11_15_fu_1540_p2 | icmp_ln10_15_fu_1534_p2);

assign or_ln10_1_fu_678_p2 = (icmp_ln11_1_fu_660_p2 | icmp_ln10_1_fu_654_p2);

assign or_ln10_2_fu_726_p2 = (icmp_ln11_2_fu_708_p2 | icmp_ln10_2_fu_702_p2);

assign or_ln10_3_fu_774_p2 = (icmp_ln11_3_fu_756_p2 | icmp_ln10_3_fu_750_p2);

assign or_ln10_4_fu_822_p2 = (icmp_ln11_4_fu_804_p2 | icmp_ln10_4_fu_798_p2);

assign or_ln10_5_fu_870_p2 = (icmp_ln11_5_fu_852_p2 | icmp_ln10_5_fu_846_p2);

assign or_ln10_6_fu_918_p2 = (icmp_ln11_6_fu_900_p2 | icmp_ln10_6_fu_894_p2);

assign or_ln10_7_fu_966_p2 = (icmp_ln11_7_fu_948_p2 | icmp_ln10_7_fu_942_p2);

assign or_ln10_8_fu_1040_p2 = (icmp_ln11_8_fu_1022_p2 | icmp_ln10_8_fu_1016_p2);

assign or_ln10_9_fu_1114_p2 = (icmp_ln11_9_fu_1096_p2 | icmp_ln10_9_fu_1090_p2);

assign or_ln10_fu_630_p2 = (icmp_ln11_fu_612_p2 | icmp_ln10_fu_606_p2);

assign s_1_fu_346_p2 = ($signed(sext_ln197_1_fu_170_p1) - $signed(sext_ln219_fu_342_p1));

assign s_2_fu_386_p2 = ($signed(sext_ln197_2_fu_174_p1) - $signed(sext_ln220_1_fu_382_p1));

assign s_3_fu_426_p2 = ($signed(sext_ln197_3_fu_178_p1) - $signed(sext_ln221_1_fu_422_p1));

assign s_4_fu_466_p2 = ($signed(sext_ln197_4_fu_182_p1) - $signed(sext_ln222_1_fu_462_p1));

assign s_5_fu_506_p2 = ($signed(sext_ln197_5_fu_186_p1) - $signed(sext_ln223_1_fu_502_p1));

assign s_6_fu_546_p2 = ($signed(sext_ln197_6_fu_190_p1) - $signed(sext_ln224_1_fu_542_p1));

assign s_7_fu_586_p2 = ($signed(sext_ln197_7_fu_194_p1) - $signed(sext_ln225_1_fu_582_p1));

assign s_fu_316_p2 = ($signed(sext_ln197_fu_166_p1) - $signed(sext_ln218_1_fu_312_p1));

assign select_ln10_10_fu_862_p3 = ((icmp_ln10_5_fu_846_p2[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign select_ln10_11_fu_876_p3 = ((or_ln10_5_fu_870_p2[0:0] == 1'b1) ? select_ln10_10_fu_862_p3 : trunc_ln12_5_fu_858_p1);

assign select_ln10_12_fu_910_p3 = ((icmp_ln10_6_fu_894_p2[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign select_ln10_13_fu_924_p3 = ((or_ln10_6_fu_918_p2[0:0] == 1'b1) ? select_ln10_12_fu_910_p3 : trunc_ln12_6_fu_906_p1);

assign select_ln10_14_fu_958_p3 = ((icmp_ln10_7_fu_942_p2[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign select_ln10_15_fu_972_p3 = ((or_ln10_7_fu_966_p2[0:0] == 1'b1) ? select_ln10_14_fu_958_p3 : trunc_ln12_7_fu_954_p1);

assign select_ln10_16_fu_1032_p3 = ((icmp_ln10_8_fu_1016_p2[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign select_ln10_17_fu_1046_p3 = ((or_ln10_8_fu_1040_p2[0:0] == 1'b1) ? select_ln10_16_fu_1032_p3 : trunc_ln12_8_fu_1028_p1);

assign select_ln10_18_fu_1106_p3 = ((icmp_ln10_9_fu_1090_p2[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign select_ln10_19_fu_1120_p3 = ((or_ln10_9_fu_1114_p2[0:0] == 1'b1) ? select_ln10_18_fu_1106_p3 : trunc_ln12_9_fu_1102_p1);

assign select_ln10_1_fu_636_p3 = ((or_ln10_fu_630_p2[0:0] == 1'b1) ? select_ln10_fu_622_p3 : trunc_ln12_fu_618_p1);

assign select_ln10_20_fu_1180_p3 = ((icmp_ln10_10_fu_1164_p2[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign select_ln10_21_fu_1194_p3 = ((or_ln10_10_fu_1188_p2[0:0] == 1'b1) ? select_ln10_20_fu_1180_p3 : trunc_ln12_10_fu_1176_p1);

assign select_ln10_22_fu_1254_p3 = ((icmp_ln10_11_fu_1238_p2[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign select_ln10_23_fu_1268_p3 = ((or_ln10_11_fu_1262_p2[0:0] == 1'b1) ? select_ln10_22_fu_1254_p3 : trunc_ln12_11_fu_1250_p1);

assign select_ln10_24_fu_1328_p3 = ((icmp_ln10_12_fu_1312_p2[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign select_ln10_25_fu_1342_p3 = ((or_ln10_12_fu_1336_p2[0:0] == 1'b1) ? select_ln10_24_fu_1328_p3 : trunc_ln12_12_fu_1324_p1);

assign select_ln10_26_fu_1402_p3 = ((icmp_ln10_13_fu_1386_p2[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign select_ln10_27_fu_1416_p3 = ((or_ln10_13_fu_1410_p2[0:0] == 1'b1) ? select_ln10_26_fu_1402_p3 : trunc_ln12_13_fu_1398_p1);

assign select_ln10_28_fu_1476_p3 = ((icmp_ln10_14_fu_1460_p2[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign select_ln10_29_fu_1490_p3 = ((or_ln10_14_fu_1484_p2[0:0] == 1'b1) ? select_ln10_28_fu_1476_p3 : trunc_ln12_14_fu_1472_p1);

assign select_ln10_2_fu_670_p3 = ((icmp_ln10_1_fu_654_p2[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign select_ln10_30_fu_1550_p3 = ((icmp_ln10_15_fu_1534_p2[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign select_ln10_31_fu_1564_p3 = ((or_ln10_15_fu_1558_p2[0:0] == 1'b1) ? select_ln10_30_fu_1550_p3 : trunc_ln12_15_fu_1546_p1);

assign select_ln10_3_fu_684_p3 = ((or_ln10_1_fu_678_p2[0:0] == 1'b1) ? select_ln10_2_fu_670_p3 : trunc_ln12_1_fu_666_p1);

assign select_ln10_4_fu_718_p3 = ((icmp_ln10_2_fu_702_p2[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign select_ln10_5_fu_732_p3 = ((or_ln10_2_fu_726_p2[0:0] == 1'b1) ? select_ln10_4_fu_718_p3 : trunc_ln12_2_fu_714_p1);

assign select_ln10_6_fu_766_p3 = ((icmp_ln10_3_fu_750_p2[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign select_ln10_7_fu_780_p3 = ((or_ln10_3_fu_774_p2[0:0] == 1'b1) ? select_ln10_6_fu_766_p3 : trunc_ln12_3_fu_762_p1);

assign select_ln10_8_fu_814_p3 = ((icmp_ln10_4_fu_798_p2[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign select_ln10_9_fu_828_p3 = ((or_ln10_4_fu_822_p2[0:0] == 1'b1) ? select_ln10_8_fu_814_p3 : trunc_ln12_4_fu_810_p1);

assign select_ln10_fu_622_p3 = ((icmp_ln10_fu_606_p2[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign sext_ln197_10_fu_392_p1 = s_2_fu_386_p2;

assign sext_ln197_11_fu_432_p1 = s_3_fu_426_p2;

assign sext_ln197_12_fu_472_p1 = s_4_fu_466_p2;

assign sext_ln197_13_fu_512_p1 = s_5_fu_506_p2;

assign sext_ln197_14_fu_552_p1 = s_6_fu_546_p2;

assign sext_ln197_15_fu_592_p1 = s_7_fu_586_p2;

assign sext_ln197_1_fu_170_p1 = $signed(low_read_23);

assign sext_ln197_2_fu_174_p1 = $signed(low_read_24);

assign sext_ln197_3_fu_178_p1 = $signed(low_read_25);

assign sext_ln197_4_fu_182_p1 = $signed(low_read_26);

assign sext_ln197_5_fu_186_p1 = $signed(low_read_27);

assign sext_ln197_6_fu_190_p1 = $signed(low_read_28);

assign sext_ln197_7_fu_194_p1 = $signed(low_read_29);

assign sext_ln197_8_fu_322_p1 = s_fu_316_p2;

assign sext_ln197_9_fu_352_p1 = s_1_fu_346_p2;

assign sext_ln197_fu_166_p1 = $signed(low_read);

assign sext_ln198_10_fu_266_p1 = sext_ln198_10_fu_266_p0;

assign sext_ln198_11_fu_270_p1 = sext_ln198_11_fu_270_p0;

assign sext_ln198_12_fu_278_p1 = sext_ln198_12_fu_278_p0;

assign sext_ln198_13_fu_282_p1 = sext_ln198_13_fu_282_p0;

assign sext_ln198_1_fu_210_p1 = sext_ln198_1_fu_210_p0;

assign sext_ln198_2_fu_218_p1 = sext_ln198_2_fu_218_p0;

assign sext_ln198_3_fu_222_p1 = sext_ln198_3_fu_222_p0;

assign sext_ln198_4_fu_230_p1 = sext_ln198_4_fu_230_p0;

assign sext_ln198_5_fu_234_p1 = sext_ln198_5_fu_234_p0;

assign sext_ln198_6_fu_242_p1 = sext_ln198_6_fu_242_p0;

assign sext_ln198_7_fu_246_p1 = sext_ln198_7_fu_246_p0;

assign sext_ln198_8_fu_254_p1 = sext_ln198_8_fu_254_p0;

assign sext_ln198_9_fu_258_p1 = sext_ln198_9_fu_258_p0;

assign sext_ln198_fu_202_p1 = sext_ln198_fu_202_p0;

assign sext_ln209_fu_198_p1 = sext_ln209_fu_198_p0;

assign sext_ln210_fu_206_p1 = sext_ln210_fu_206_p0;

assign sext_ln211_fu_214_p1 = sext_ln211_fu_214_p0;

assign sext_ln212_fu_226_p1 = sext_ln212_fu_226_p0;

assign sext_ln213_fu_238_p1 = sext_ln213_fu_238_p0;

assign sext_ln214_fu_250_p1 = sext_ln214_fu_250_p0;

assign sext_ln215_fu_262_p1 = sext_ln215_fu_262_p0;

assign sext_ln216_fu_274_p1 = sext_ln216_fu_274_p0;

assign sext_ln218_1_fu_312_p1 = $signed(trunc_ln_fu_302_p4);

assign sext_ln218_fu_292_p1 = $signed(add_ln218_fu_286_p2);

assign sext_ln219_fu_342_p1 = $signed(trunc_ln1_fu_332_p4);

assign sext_ln220_1_fu_382_p1 = $signed(trunc_ln2_fu_372_p4);

assign sext_ln220_fu_362_p1 = $signed(add_ln220_fu_356_p2);

assign sext_ln221_1_fu_422_p1 = $signed(trunc_ln3_fu_412_p4);

assign sext_ln221_fu_402_p1 = $signed(add_ln221_fu_396_p2);

assign sext_ln222_1_fu_462_p1 = $signed(trunc_ln4_fu_452_p4);

assign sext_ln222_fu_442_p1 = $signed(add_ln222_fu_436_p2);

assign sext_ln223_1_fu_502_p1 = $signed(trunc_ln5_fu_492_p4);

assign sext_ln223_fu_482_p1 = $signed(add_ln223_fu_476_p2);

assign sext_ln224_1_fu_542_p1 = $signed(trunc_ln6_fu_532_p4);

assign sext_ln224_fu_522_p1 = $signed(add_ln224_fu_516_p2);

assign sext_ln225_1_fu_582_p1 = $signed(trunc_ln7_fu_572_p4);

assign sext_ln225_fu_562_p1 = $signed(add_ln225_fu_556_p2);

assign sext_ln236_fu_996_p1 = $signed(tmp_8_fu_986_p4);

assign sext_ln237_fu_1070_p1 = $signed(tmp_10_fu_1060_p4);

assign sext_ln238_fu_1144_p1 = $signed(tmp_12_fu_1134_p4);

assign sext_ln239_fu_1218_p1 = $signed(tmp_14_fu_1208_p4);

assign sext_ln240_fu_1292_p1 = $signed(tmp_16_fu_1282_p4);

assign sext_ln241_fu_1366_p1 = $signed(tmp_18_fu_1356_p4);

assign sext_ln242_fu_1440_p1 = $signed(tmp_20_fu_1430_p4);

assign sext_ln243_fu_1514_p1 = $signed(tmp_22_fu_1504_p4);

assign tmp_10_fu_1060_p4 = {{add_ln237_fu_1054_p2[17:1]}};

assign tmp_11_fu_1080_p4 = {{add_ln237_1_fu_1074_p2[31:7]}};

assign tmp_12_fu_1134_p4 = {{add_ln238_fu_1128_p2[17:1]}};

assign tmp_13_fu_1154_p4 = {{add_ln238_1_fu_1148_p2[31:7]}};

assign tmp_14_fu_1208_p4 = {{add_ln239_fu_1202_p2[17:1]}};

assign tmp_15_fu_1228_p4 = {{add_ln239_1_fu_1222_p2[31:7]}};

assign tmp_16_fu_1282_p4 = {{add_ln240_fu_1276_p2[17:1]}};

assign tmp_17_fu_1302_p4 = {{add_ln240_1_fu_1296_p2[31:7]}};

assign tmp_18_fu_1356_p4 = {{add_ln241_fu_1350_p2[17:1]}};

assign tmp_19_fu_1376_p4 = {{add_ln241_1_fu_1370_p2[31:7]}};

assign tmp_1_fu_644_p4 = {{s_1_fu_346_p2[16:7]}};

assign tmp_20_fu_1430_p4 = {{add_ln242_fu_1424_p2[17:1]}};

assign tmp_21_fu_1450_p4 = {{add_ln242_1_fu_1444_p2[31:7]}};

assign tmp_22_fu_1504_p4 = {{add_ln243_fu_1498_p2[17:1]}};

assign tmp_23_fu_1524_p4 = {{add_ln243_1_fu_1518_p2[31:7]}};

assign tmp_2_fu_692_p4 = {{s_2_fu_386_p2[16:7]}};

assign tmp_3_fu_740_p4 = {{s_3_fu_426_p2[16:7]}};

assign tmp_4_fu_788_p4 = {{s_4_fu_466_p2[16:7]}};

assign tmp_5_fu_836_p4 = {{s_5_fu_506_p2[16:7]}};

assign tmp_6_fu_884_p4 = {{s_6_fu_546_p2[16:7]}};

assign tmp_7_fu_932_p4 = {{s_7_fu_586_p2[16:7]}};

assign tmp_8_fu_986_p4 = {{add_ln236_fu_980_p2[17:1]}};

assign tmp_9_fu_1006_p4 = {{add_ln236_1_fu_1000_p2[31:7]}};

assign tmp_fu_596_p4 = {{s_fu_316_p2[16:7]}};

assign trunc_ln12_10_fu_1176_p1 = add_ln238_1_fu_1148_p2[7:0];

assign trunc_ln12_11_fu_1250_p1 = add_ln239_1_fu_1222_p2[7:0];

assign trunc_ln12_12_fu_1324_p1 = add_ln240_1_fu_1296_p2[7:0];

assign trunc_ln12_13_fu_1398_p1 = add_ln241_1_fu_1370_p2[7:0];

assign trunc_ln12_14_fu_1472_p1 = add_ln242_1_fu_1444_p2[7:0];

assign trunc_ln12_15_fu_1546_p1 = add_ln243_1_fu_1518_p2[7:0];

assign trunc_ln12_1_fu_666_p1 = s_1_fu_346_p2[7:0];

assign trunc_ln12_2_fu_714_p1 = s_2_fu_386_p2[7:0];

assign trunc_ln12_3_fu_762_p1 = s_3_fu_426_p2[7:0];

assign trunc_ln12_4_fu_810_p1 = s_4_fu_466_p2[7:0];

assign trunc_ln12_5_fu_858_p1 = s_5_fu_506_p2[7:0];

assign trunc_ln12_6_fu_906_p1 = s_6_fu_546_p2[7:0];

assign trunc_ln12_7_fu_954_p1 = s_7_fu_586_p2[7:0];

assign trunc_ln12_8_fu_1028_p1 = add_ln236_1_fu_1000_p2[7:0];

assign trunc_ln12_9_fu_1102_p1 = add_ln237_1_fu_1074_p2[7:0];

assign trunc_ln12_fu_618_p1 = s_fu_316_p2[7:0];

assign trunc_ln1_fu_332_p4 = {{add_ln219_fu_326_p2[17:2]}};

assign trunc_ln2_fu_372_p4 = {{add_ln220_1_fu_366_p2[17:2]}};

assign trunc_ln3_fu_412_p4 = {{add_ln221_1_fu_406_p2[17:2]}};

assign trunc_ln4_fu_452_p4 = {{add_ln222_1_fu_446_p2[17:2]}};

assign trunc_ln5_fu_492_p4 = {{add_ln223_1_fu_486_p2[17:2]}};

assign trunc_ln6_fu_532_p4 = {{add_ln224_1_fu_526_p2[17:2]}};

assign trunc_ln7_fu_572_p4 = {{add_ln225_1_fu_566_p2[17:2]}};

assign trunc_ln_fu_302_p4 = {{add_ln218_1_fu_296_p2[17:2]}};

assign ap_return_0 = select_ln10_1_fu_636_p3;

assign ap_return_1 = select_ln10_17_fu_1046_p3;

assign ap_return_10 = select_ln10_11_fu_876_p3;

assign ap_return_11 = select_ln10_27_fu_1416_p3;

assign ap_return_12 = select_ln10_13_fu_924_p3;

assign ap_return_13 = select_ln10_29_fu_1490_p3;

assign ap_return_14 = select_ln10_15_fu_972_p3;

assign ap_return_15 = select_ln10_31_fu_1564_p3;

assign ap_return_2 = select_ln10_3_fu_684_p3;

assign ap_return_3 = select_ln10_19_fu_1120_p3;

assign ap_return_4 = select_ln10_5_fu_732_p3;

assign ap_return_5 = select_ln10_21_fu_1194_p3;

assign ap_return_6 = select_ln10_7_fu_780_p3;

assign ap_return_7 = select_ln10_23_fu_1268_p3;

assign ap_return_8 = select_ln10_9_fu_828_p3;

assign ap_return_9 = select_ln10_25_fu_1342_p3;

assign icmp_ln10_10_fu_1164_p2 = (($signed(tmp_13_fu_1154_p4) > $signed(25'd0)) ? 1'b1 : 1'b0);

assign icmp_ln10_11_fu_1238_p2 = (($signed(tmp_15_fu_1228_p4) > $signed(25'd0)) ? 1'b1 : 1'b0);

assign icmp_ln10_12_fu_1312_p2 = (($signed(tmp_17_fu_1302_p4) > $signed(25'd0)) ? 1'b1 : 1'b0);

assign icmp_ln10_13_fu_1386_p2 = (($signed(tmp_19_fu_1376_p4) > $signed(25'd0)) ? 1'b1 : 1'b0);

assign icmp_ln10_14_fu_1460_p2 = (($signed(tmp_21_fu_1450_p4) > $signed(25'd0)) ? 1'b1 : 1'b0);

assign icmp_ln10_15_fu_1534_p2 = (($signed(tmp_23_fu_1524_p4) > $signed(25'd0)) ? 1'b1 : 1'b0);

assign icmp_ln10_1_fu_654_p2 = (($signed(tmp_1_fu_644_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln10_2_fu_702_p2 = (($signed(tmp_2_fu_692_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln10_3_fu_750_p2 = (($signed(tmp_3_fu_740_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln10_4_fu_798_p2 = (($signed(tmp_4_fu_788_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln10_5_fu_846_p2 = (($signed(tmp_5_fu_836_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln10_6_fu_894_p2 = (($signed(tmp_6_fu_884_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln10_7_fu_942_p2 = (($signed(tmp_7_fu_932_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln10_8_fu_1016_p2 = (($signed(tmp_9_fu_1006_p4) > $signed(25'd0)) ? 1'b1 : 1'b0);

assign icmp_ln10_9_fu_1090_p2 = (($signed(tmp_11_fu_1080_p4) > $signed(25'd0)) ? 1'b1 : 1'b0);

assign icmp_ln10_fu_606_p2 = (($signed(tmp_fu_596_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln11_10_fu_1170_p2 = (($signed(add_ln238_1_fu_1148_p2) < $signed(32'd4294967168)) ? 1'b1 : 1'b0);

assign icmp_ln11_11_fu_1244_p2 = (($signed(add_ln239_1_fu_1222_p2) < $signed(32'd4294967168)) ? 1'b1 : 1'b0);

assign icmp_ln11_12_fu_1318_p2 = (($signed(add_ln240_1_fu_1296_p2) < $signed(32'd4294967168)) ? 1'b1 : 1'b0);

assign icmp_ln11_13_fu_1392_p2 = (($signed(add_ln241_1_fu_1370_p2) < $signed(32'd4294967168)) ? 1'b1 : 1'b0);

assign icmp_ln11_14_fu_1466_p2 = (($signed(add_ln242_1_fu_1444_p2) < $signed(32'd4294967168)) ? 1'b1 : 1'b0);

assign icmp_ln11_15_fu_1540_p2 = (($signed(add_ln243_1_fu_1518_p2) < $signed(32'd4294967168)) ? 1'b1 : 1'b0);

assign icmp_ln11_1_fu_660_p2 = (($signed(s_1_fu_346_p2) < $signed(17'd130944)) ? 1'b1 : 1'b0);

assign icmp_ln11_2_fu_708_p2 = (($signed(s_2_fu_386_p2) < $signed(17'd130944)) ? 1'b1 : 1'b0);

assign icmp_ln11_3_fu_756_p2 = (($signed(s_3_fu_426_p2) < $signed(17'd130944)) ? 1'b1 : 1'b0);

assign icmp_ln11_4_fu_804_p2 = (($signed(s_4_fu_466_p2) < $signed(17'd130944)) ? 1'b1 : 1'b0);

assign icmp_ln11_5_fu_852_p2 = (($signed(s_5_fu_506_p2) < $signed(17'd130944)) ? 1'b1 : 1'b0);

assign icmp_ln11_6_fu_900_p2 = (($signed(s_6_fu_546_p2) < $signed(17'd130944)) ? 1'b1 : 1'b0);

assign icmp_ln11_7_fu_948_p2 = (($signed(s_7_fu_586_p2) < $signed(17'd130944)) ? 1'b1 : 1'b0);

assign icmp_ln11_8_fu_1022_p2 = (($signed(add_ln236_1_fu_1000_p2) < $signed(32'd4294967168)) ? 1'b1 : 1'b0);

assign icmp_ln11_9_fu_1096_p2 = (($signed(add_ln237_1_fu_1074_p2) < $signed(32'd4294967168)) ? 1'b1 : 1'b0);

assign icmp_ln11_fu_612_p2 = (($signed(s_fu_316_p2) < $signed(17'd130944)) ? 1'b1 : 1'b0);

assign sext_ln198_10_fu_266_p0 = high_read_28;

assign sext_ln198_11_fu_270_p0 = high_read_28;

assign sext_ln198_12_fu_278_p0 = high_read_29;

assign sext_ln198_13_fu_282_p0 = high_read_29;

assign sext_ln198_1_fu_210_p0 = high_read_23;

assign sext_ln198_2_fu_218_p0 = high_read_24;

assign sext_ln198_3_fu_222_p0 = high_read_24;

assign sext_ln198_4_fu_230_p0 = high_read_25;

assign sext_ln198_5_fu_234_p0 = high_read_25;

assign sext_ln198_6_fu_242_p0 = high_read_26;

assign sext_ln198_7_fu_246_p0 = high_read_26;

assign sext_ln198_8_fu_254_p0 = high_read_27;

assign sext_ln198_9_fu_258_p0 = high_read_27;

assign sext_ln198_fu_202_p0 = high_read;

assign sext_ln209_fu_198_p0 = high_read;

assign sext_ln210_fu_206_p0 = high_read_23;

assign sext_ln211_fu_214_p0 = high_read_24;

assign sext_ln212_fu_226_p0 = high_read_25;

assign sext_ln213_fu_238_p0 = high_read_26;

assign sext_ln214_fu_250_p0 = high_read_27;

assign sext_ln215_fu_262_p0 = high_read_28;

assign sext_ln216_fu_274_p0 = high_read_29;

endmodule //HW_dwt53_inverse_HW_dwt53_inverse_core
