// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="HW_idwt_db8_int16_HW_idwt_db8_int16,hls_ip_2024_2,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcku5p-ffvb676-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.647625,HLS_SYN_LAT=5,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1481,HLS_SYN_LUT=7171,HLS_VERSION=2024_2}" *)

module HW_idwt_db8_int16 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        low_03,
        low_47,
        high_03,
        high_47,
        p_out_0,
        p_out_0_ap_vld,
        p_out_1,
        p_out_1_ap_vld
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] low_03;
input  [63:0] low_47;
input  [63:0] high_03;
input  [63:0] high_47;
output  [63:0] p_out_0;
output   p_out_0_ap_vld;
output  [63:0] p_out_1;
output   p_out_1_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_out_0_ap_vld;
reg p_out_1_ap_vld;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [15:0] in_low_reg_366;
reg   [15:0] in_low_1_reg_371;
reg   [15:0] in_low_2_reg_376;
wire   [15:0] in_low_3_fu_141_p1;
reg   [15:0] in_low_3_reg_381;
reg   [15:0] in_low_4_reg_386;
reg   [15:0] in_low_5_reg_391;
reg   [15:0] in_low_6_reg_396;
wire   [15:0] in_low_7_fu_179_p1;
reg   [15:0] in_low_7_reg_401;
reg   [15:0] in_high_reg_406;
reg   [15:0] in_high_1_reg_411;
reg   [15:0] in_high_2_reg_416;
wire   [15:0] in_high_3_fu_217_p1;
reg   [15:0] in_high_3_reg_421;
reg   [15:0] in_high_4_reg_426;
reg   [15:0] in_high_5_reg_431;
reg   [15:0] in_high_6_reg_436;
wire   [15:0] in_high_7_fu_255_p1;
reg   [15:0] in_high_7_reg_441;
wire    grp_HW_idwt_db8_int16_core_fu_88_ap_start;
wire    grp_HW_idwt_db8_int16_core_fu_88_ap_done;
wire    grp_HW_idwt_db8_int16_core_fu_88_ap_idle;
wire    grp_HW_idwt_db8_int16_core_fu_88_ap_ready;
wire   [7:0] grp_HW_idwt_db8_int16_core_fu_88_ap_return_0;
wire   [7:0] grp_HW_idwt_db8_int16_core_fu_88_ap_return_1;
wire   [7:0] grp_HW_idwt_db8_int16_core_fu_88_ap_return_2;
wire   [7:0] grp_HW_idwt_db8_int16_core_fu_88_ap_return_3;
wire   [7:0] grp_HW_idwt_db8_int16_core_fu_88_ap_return_4;
wire   [7:0] grp_HW_idwt_db8_int16_core_fu_88_ap_return_5;
wire   [7:0] grp_HW_idwt_db8_int16_core_fu_88_ap_return_6;
wire   [7:0] grp_HW_idwt_db8_int16_core_fu_88_ap_return_7;
wire   [7:0] grp_HW_idwt_db8_int16_core_fu_88_ap_return_8;
wire   [7:0] grp_HW_idwt_db8_int16_core_fu_88_ap_return_9;
wire   [7:0] grp_HW_idwt_db8_int16_core_fu_88_ap_return_10;
wire   [7:0] grp_HW_idwt_db8_int16_core_fu_88_ap_return_11;
wire   [7:0] grp_HW_idwt_db8_int16_core_fu_88_ap_return_12;
wire   [7:0] grp_HW_idwt_db8_int16_core_fu_88_ap_return_13;
wire   [7:0] grp_HW_idwt_db8_int16_core_fu_88_ap_return_14;
wire   [7:0] grp_HW_idwt_db8_int16_core_fu_88_ap_return_15;
reg    grp_HW_idwt_db8_int16_core_fu_88_ap_start_reg;
wire    ap_CS_fsm_state2;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 grp_HW_idwt_db8_int16_core_fu_88_ap_start_reg = 1'b0;
end

HW_idwt_db8_int16_HW_idwt_db8_int16_core grp_HW_idwt_db8_int16_core_fu_88(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_HW_idwt_db8_int16_core_fu_88_ap_start),
    .ap_done(grp_HW_idwt_db8_int16_core_fu_88_ap_done),
    .ap_idle(grp_HW_idwt_db8_int16_core_fu_88_ap_idle),
    .ap_ready(grp_HW_idwt_db8_int16_core_fu_88_ap_ready),
    .low_read(in_low_reg_366),
    .low_read_23(in_low_1_reg_371),
    .low_read_24(in_low_2_reg_376),
    .low_read_25(in_low_3_reg_381),
    .low_read_26(in_low_4_reg_386),
    .low_read_27(in_low_5_reg_391),
    .low_read_28(in_low_6_reg_396),
    .low_read_29(in_low_7_reg_401),
    .high_read(in_high_reg_406),
    .high_read_23(in_high_1_reg_411),
    .high_read_24(in_high_2_reg_416),
    .high_read_25(in_high_3_reg_421),
    .high_read_26(in_high_4_reg_426),
    .high_read_27(in_high_5_reg_431),
    .high_read_28(in_high_6_reg_436),
    .high_read_29(in_high_7_reg_441),
    .ap_return_0(grp_HW_idwt_db8_int16_core_fu_88_ap_return_0),
    .ap_return_1(grp_HW_idwt_db8_int16_core_fu_88_ap_return_1),
    .ap_return_2(grp_HW_idwt_db8_int16_core_fu_88_ap_return_2),
    .ap_return_3(grp_HW_idwt_db8_int16_core_fu_88_ap_return_3),
    .ap_return_4(grp_HW_idwt_db8_int16_core_fu_88_ap_return_4),
    .ap_return_5(grp_HW_idwt_db8_int16_core_fu_88_ap_return_5),
    .ap_return_6(grp_HW_idwt_db8_int16_core_fu_88_ap_return_6),
    .ap_return_7(grp_HW_idwt_db8_int16_core_fu_88_ap_return_7),
    .ap_return_8(grp_HW_idwt_db8_int16_core_fu_88_ap_return_8),
    .ap_return_9(grp_HW_idwt_db8_int16_core_fu_88_ap_return_9),
    .ap_return_10(grp_HW_idwt_db8_int16_core_fu_88_ap_return_10),
    .ap_return_11(grp_HW_idwt_db8_int16_core_fu_88_ap_return_11),
    .ap_return_12(grp_HW_idwt_db8_int16_core_fu_88_ap_return_12),
    .ap_return_13(grp_HW_idwt_db8_int16_core_fu_88_ap_return_13),
    .ap_return_14(grp_HW_idwt_db8_int16_core_fu_88_ap_return_14),
    .ap_return_15(grp_HW_idwt_db8_int16_core_fu_88_ap_return_15)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_HW_idwt_db8_int16_core_fu_88_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_HW_idwt_db8_int16_core_fu_88_ap_start_reg <= 1'b1;
        end else if ((grp_HW_idwt_db8_int16_core_fu_88_ap_ready == 1'b1)) begin
            grp_HW_idwt_db8_int16_core_fu_88_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        in_high_1_reg_411 <= {{high_03[47:32]}};
        in_high_2_reg_416 <= {{high_03[31:16]}};
        in_high_3_reg_421 <= in_high_3_fu_217_p1;
        in_high_4_reg_426 <= {{high_47[63:48]}};
        in_high_5_reg_431 <= {{high_47[47:32]}};
        in_high_6_reg_436 <= {{high_47[31:16]}};
        in_high_7_reg_441 <= in_high_7_fu_255_p1;
        in_high_reg_406 <= {{high_03[63:48]}};
        in_low_1_reg_371 <= {{low_03[47:32]}};
        in_low_2_reg_376 <= {{low_03[31:16]}};
        in_low_3_reg_381 <= in_low_3_fu_141_p1;
        in_low_4_reg_386 <= {{low_47[63:48]}};
        in_low_5_reg_391 <= {{low_47[47:32]}};
        in_low_6_reg_396 <= {{low_47[31:16]}};
        in_low_7_reg_401 <= in_low_7_fu_179_p1;
        in_low_reg_366 <= {{low_03[63:48]}};
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_HW_idwt_db8_int16_core_fu_88_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_HW_idwt_db8_int16_core_fu_88_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_HW_idwt_db8_int16_core_fu_88_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((grp_HW_idwt_db8_int16_core_fu_88_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        p_out_0_ap_vld = 1'b1;
    end else begin
        p_out_0_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_HW_idwt_db8_int16_core_fu_88_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        p_out_1_ap_vld = 1'b1;
    end else begin
        p_out_1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_HW_idwt_db8_int16_core_fu_88_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign grp_HW_idwt_db8_int16_core_fu_88_ap_start = grp_HW_idwt_db8_int16_core_fu_88_ap_start_reg;

assign in_high_3_fu_217_p1 = high_03[15:0];

assign in_high_7_fu_255_p1 = high_47[15:0];

assign in_low_3_fu_141_p1 = low_03[15:0];

assign in_low_7_fu_179_p1 = low_47[15:0];

assign p_out_0 = {{{{{{{{grp_HW_idwt_db8_int16_core_fu_88_ap_return_0}, {grp_HW_idwt_db8_int16_core_fu_88_ap_return_1}}, {grp_HW_idwt_db8_int16_core_fu_88_ap_return_2}}, {grp_HW_idwt_db8_int16_core_fu_88_ap_return_3}}, {grp_HW_idwt_db8_int16_core_fu_88_ap_return_4}}, {grp_HW_idwt_db8_int16_core_fu_88_ap_return_5}}, {grp_HW_idwt_db8_int16_core_fu_88_ap_return_6}}, {grp_HW_idwt_db8_int16_core_fu_88_ap_return_7}};

assign p_out_1 = {{{{{{{{grp_HW_idwt_db8_int16_core_fu_88_ap_return_8}, {grp_HW_idwt_db8_int16_core_fu_88_ap_return_9}}, {grp_HW_idwt_db8_int16_core_fu_88_ap_return_10}}, {grp_HW_idwt_db8_int16_core_fu_88_ap_return_11}}, {grp_HW_idwt_db8_int16_core_fu_88_ap_return_12}}, {grp_HW_idwt_db8_int16_core_fu_88_ap_return_13}}, {grp_HW_idwt_db8_int16_core_fu_88_ap_return_14}}, {grp_HW_idwt_db8_int16_core_fu_88_ap_return_15}};

endmodule //HW_idwt_db8_int16
